import "server-only";
import type { AuthProfile } from "@/features/auth/types/auth";
import type { AdmissionFeeOverride, FeeNature, FeeScheduleType, FeeStructure, FeeStructureOption } from "@/features/fees/types/fee-structure";
import type { FeeStructureValues } from "@/features/fees/validations/fee-structure-schema";
import { createClient } from "@/lib/supabase/server";

const one=<T>(v:T|T[]|null):T|null=>!v?null:Array.isArray(v)?v[0]??null:v;
function institute(profile:AuthProfile){if(!profile.instituteId)throw new Error("FEES_UNAUTHORIZED");return profile.instituteId}
interface Row { id:string;name:string;academic_year_id:string;class_id:string;is_active:boolean;updated_at:string;year:{name:string}|{name:string}[]|null;academic_class:{class_name:string}|{class_name:string}[]|null;items:Array<{id:string;fee_head_id:string;amount:number;is_mandatory:boolean;default_discount_type:"fixed"|"percentage"|null;default_discount_value:number;schedule_type:FeeScheduleType;display_order:number;head:{name:string;fee_nature:FeeNature}|{name:string;fee_nature:FeeNature}[]|null;installments:Array<{installment_no:number;due_date:string;gross_amount:number}>;assignments:Array<{id:string}>}> }
const SELECT="id,name,academic_year_id,class_id,is_active,updated_at,year:academic_years!class_fee_structures_year_fkey(name),academic_class:academic_classes!class_fee_structures_class_fkey(class_name),items:class_fee_structure_items!class_fee_structure_items_structure_fkey(id,fee_head_id,amount,is_mandatory,default_discount_type,default_discount_value,schedule_type,display_order,head:fee_heads!class_fee_structure_items_head_fkey(name,fee_nature),installments:class_fee_structure_installments!class_fee_installments_item_fkey(installment_no,due_date,gross_amount),assignments:student_fee_assignments(id))";
function map(row:Row):FeeStructure{return{id:row.id,name:row.name,academicYearId:row.academic_year_id,academicYearName:one(row.year)?.name??"ACADEMIC YEAR",classId:row.class_id,className:one(row.academic_class)?.class_name??"CLASS",isActive:row.is_active,isInUse:row.items.some(i=>(i.assignments?.length??0)>0),updatedAt:row.updated_at,items:(row.items??[]).sort((a,b)=>a.display_order-b.display_order).map(i=>({id:i.id,feeHeadId:i.fee_head_id,feeHeadName:one(i.head)?.name??"FEE HEAD",feeNature:one(i.head)?.fee_nature??"regular",amount:Number(i.amount),isMandatory:i.is_mandatory,defaultDiscountType:i.default_discount_type,defaultDiscountValue:Number(i.default_discount_value),scheduleType:i.schedule_type,displayOrder:i.display_order,installments:(i.installments??[]).sort((a,b)=>a.installment_no-b.installment_no).map(x=>({installmentNo:x.installment_no,dueDate:x.due_date,grossAmount:Number(x.gross_amount)}))}))}}
export async function listFeeStructures(profile:AuthProfile):Promise<FeeStructure[]>{const s=await createClient();const{data,error}=await s.from("class_fee_structures").select(SELECT).eq("institute_id",institute(profile)).order("updated_at",{ascending:false});if(error)throw error;return(data as unknown as Row[]).map(map)}
export async function findFeeStructure(profile:AuthProfile,yearId:string,classId:string):Promise<FeeStructure|null>{const s=await createClient();const{data,error}=await s.from("class_fee_structures").select(SELECT).eq("institute_id",institute(profile)).eq("academic_year_id",yearId).eq("class_id",classId).eq("is_active",true).maybeSingle();if(error)throw error;return data?map(data as unknown as Row):null}
export async function getFeeStructureOptions(profile:AuthProfile){const id=institute(profile),s=await createClient();const[years,classes,heads]=await Promise.all([s.from("academic_years").select("id,name").eq("institute_id",id).eq("is_active",true).order("start_date",{ascending:false}),s.from("academic_classes").select("id,class_name").eq("institute_id",id).order("display_order"),s.from("fee_heads").select("id,name,fee_nature").eq("institute_id",id).eq("is_active",true).order("display_order")]);const error=years.error??classes.error??heads.error;if(error)throw error;return{academicYears:(years.data??[]) as FeeStructureOption[],classes:(classes.data??[]).map(x=>({id:x.id,name:x.class_name})) as FeeStructureOption[],feeHeads:(heads.data??[]).map(x=>({id:x.id,name:x.name,feeNature:x.fee_nature as FeeNature}))}}
export async function saveFeeStructure(profile:AuthProfile,values:FeeStructureValues):Promise<string>{institute(profile);const s=await createClient();const{data,error}=await s.rpc("save_class_fee_structure",{p_structure_id:values.id,p_academic_year_id:values.academicYearId,p_class_id:values.classId,p_name:values.name,p_is_active:values.isActive,p_items:values.items.map(x=>({fee_head_id:x.feeHeadId,amount:x.amount,is_mandatory:x.isMandatory,discount_type:x.discountType,discount_value:x.discountValue,schedule_type:x.scheduleType,display_order:x.displayOrder,start_due_date:x.startDueDate,installments:x.installments.map(i=>({installment_no:i.installmentNo,due_date:i.dueDate,gross_amount:i.grossAmount}))}))});if(error)throw error;return data as string}
export async function applyFeeStructure(profile:AuthProfile,studentId:string,structureId:string,overrides:AdmissionFeeOverride[]){institute(profile);const s=await createClient();const{data,error}=await s.rpc("apply_class_fee_structure",{p_student_id:studentId,p_structure_id:structureId,p_overrides:overrides});if(error)throw error;return data as{structureId:string;assignmentCount:number}}
