"use client";

import Link from "next/link";
import { useMemo, useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { Bell, CreditCard, IndianRupee, ReceiptText, RotateCcw, Send } from "lucide-react";

import { StatCard } from "@/components/dashboard/stat-card";
import { PageHeader } from "@/components/layout/page-header";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Toaster, toast } from "@/components/ui/toast";
import { createFeeAssignment, postFeePayment, queueManualFeeReminder, queueOverdueFeeReminders, reverseFeePayment, updateFeeSettings } from "@/features/fees/actions/fee-actions";
import type { FeeDue, FeeMessage, FeeOption, FeePayment, FeeSettings, FeeStudent, FeeSummary } from "@/features/fees/types/fees";

const money = new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR" });
const date = new Intl.DateTimeFormat("en-IN", { dateStyle: "medium" });
const select = "h-10 w-full rounded-2xl border border-input bg-background px-3 text-sm";
function notify(result: { status: string; message: string }) { toast.add({ title: result.status === "success" ? "Success" : "Unable to continue", description: result.message, type: result.status === "success" ? "success" : "error" }); }

export function FeesOverview({ summary }: { summary: FeeSummary }) {
  return <div className="space-y-6"><PageHeader title="Fees" description="Manage student dues, collections, receipts, and communication from one secure workspace." icon={IndianRupee} theme="fee-heads" />
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard title="Outstanding" value={money.format(summary.totalOutstanding)} description="Across active dues" icon={IndianRupee} tone="rose" href="/fees/student-fees" linkLabel="View dues" /><StatCard title="Collected Today" value={money.format(summary.collectionsToday)} description="Posted payments" icon={CreditCard} tone="emerald" href="/fees/payments" linkLabel="View payments" /><StatCard title="This Month" value={money.format(summary.collectionsThisMonth)} description="Posted collections" icon={ReceiptText} tone="blue" href="/fees/reports" linkLabel="View report" /><StatCard title="Overdue Dues" value={String(summary.overdueCount)} description="Need follow-up" icon={Bell} tone="amber" href="/fees/student-fees" linkLabel="Review" /></div>
    <div className="grid gap-4 md:grid-cols-3">{[["Student Fees","Assign fees and review outstanding dues.","/fees/student-fees"],["Collect Payment","Post an allocated payment and issue a receipt.","/fees/collect"],["WhatsApp Outbox","Review queued confirmations and reminders.","/fees/messages"]].map(([title,description,href]) => <Card key={href}><CardHeader><CardTitle>{title}</CardTitle></CardHeader><CardContent><p className="mb-4 text-sm text-muted-foreground">{description}</p><Button nativeButton={false} render={<Link href={href} />}>Open</Button></CardContent></Card>)}</div></div>;
}

export function StudentFeesManager({ students, years, heads, dues }: { students: FeeStudent[]; years: FeeOption[]; heads: FeeOption[]; dues: FeeDue[] }) {
  const [pending, start] = useTransition(); const router = useRouter(); const [studentId, setStudent] = useState(students[0]?.id ?? ""); const [yearId, setYear] = useState(years[0]?.id ?? ""); const [headId, setHead] = useState(heads[0]?.id ?? ""); const [amount, setAmount] = useState(""); const [dueDate, setDueDate] = useState(new Date().toISOString().slice(0,10));
  function submit(e: React.FormEvent) { e.preventDefault(); const gross = Number(amount); start(async () => { const result = await createFeeAssignment({ studentId, academicYearId: yearId, feeHeadId: headId, amount: gross, discountType: null, discountValue: 0, effectiveFrom: dueDate, effectiveTo: null, installments: [{ installmentNo: 1, dueDate, grossAmount: gross, discountAmount: 0, netAmount: gross }] }); notify(result); if (result.status === "success") { setAmount(""); router.refresh(); } }); }
  return <div className="space-y-6"><PageHeader title="Student Fees" description="Assign institute Fee Heads and track each Student's due history." icon={IndianRupee} theme="fee-heads" />
    <Card><CardHeader><CardTitle>Assign Fee</CardTitle></CardHeader><CardContent><form className="grid gap-4 md:grid-cols-5" onSubmit={submit}><label className="grid gap-2 text-sm">Student<select className={select} value={studentId} onChange={(e)=>setStudent(e.target.value)} required>{students.map((x)=><option key={x.id} value={x.id}>{x.name}{x.admissionNo ? ` · ${x.admissionNo}`:""}</option>)}</select></label><label className="grid gap-2 text-sm">Academic Year<select className={select} value={yearId} onChange={(e)=>setYear(e.target.value)} required>{years.map((x)=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label className="grid gap-2 text-sm">Fee Head<select className={select} value={headId} onChange={(e)=>setHead(e.target.value)} required>{heads.map((x)=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label className="grid gap-2 text-sm">Amount<Input type="number" min="0.01" step="0.01" value={amount} onChange={(e)=>setAmount(e.target.value)} required /></label><label className="grid gap-2 text-sm">Due Date<Input type="date" value={dueDate} onChange={(e)=>setDueDate(e.target.value)} required /></label><Button className="md:col-span-5 md:justify-self-end" disabled={pending}>{pending ? "Assigning…":"Assign Fee"}</Button></form></CardContent></Card>
    <DuesTable dues={dues} reminders /><Toaster /></div>;
}

function DuesTable({ dues, reminders=false }: { dues: FeeDue[]; reminders?: boolean }) { const [pending,start]=useTransition(); return <Card><CardContent className="pt-6"><div className="overflow-x-auto"><Table><TableHeader><TableRow><TableHead>Student</TableHead><TableHead>Fee Head</TableHead><TableHead>Academic Year</TableHead><TableHead>Due Date</TableHead><TableHead>Outstanding</TableHead><TableHead>Status</TableHead>{reminders?<TableHead>Action</TableHead>:null}</TableRow></TableHeader><TableBody>{dues.map((x)=><TableRow key={x.id}><TableCell>{x.studentName}<span className="block text-xs text-muted-foreground">{x.admissionNo}</span></TableCell><TableCell>{x.feeHeadName}</TableCell><TableCell>{x.academicYearName}</TableCell><TableCell>{date.format(new Date(`${x.dueDate}T00:00:00`))}</TableCell><TableCell>{money.format(x.outstanding)}</TableCell><TableCell><Badge variant={x.outstanding > 0 ? "outline":"secondary"}>{x.status.replaceAll("_"," ")}</Badge></TableCell>{reminders?<TableCell><Button size="sm" variant="outline" disabled={pending || x.outstanding <= 0} onClick={()=>start(async()=>notify(await queueManualFeeReminder({dueId:x.id})))}><Send /> Remind</Button></TableCell>:null}</TableRow>)}{dues.length===0?<TableRow><TableCell colSpan={reminders?7:6} className="py-10 text-center text-muted-foreground">No fee dues yet.</TableCell></TableRow>:null}</TableBody></Table></div></CardContent></Card> }

export function CollectPayment({ students, years, modes, dues }: { students: FeeStudent[]; years: FeeOption[]; modes: FeeOption[]; dues: FeeDue[] }) { const [pending,start]=useTransition(); const router=useRouter(); const [studentId,setStudent]=useState(students[0]?.id??""); const [yearId,setYear]=useState(years[0]?.id??""); const [modeId,setMode]=useState(modes[0]?.id??""); const [amounts,setAmounts]=useState<Record<string,string>>({}); const eligible=useMemo(()=>dues.filter((x)=>x.studentId===studentId&&x.academicYearId===yearId&&x.outstanding>0),[dues,studentId,yearId]); const total=eligible.reduce((sum,x)=>sum+Number(amounts[x.id]??0),0);
  function submit(e:React.FormEvent){e.preventDefault(); start(async()=>{const result=await postFeePayment({studentId,academicYearId:yearId,paymentModeId:modeId,paymentDate:new Date().toISOString(),referenceNo:null,remarks:null,allocations:eligible.map((x)=>({dueId:x.id,amount:Number(amounts[x.id]??0)})).filter((x)=>x.amount>0)});notify(result);if(result.status==="success"){setAmounts({});router.refresh();}})}
  return <div className="space-y-6"><PageHeader title="Collect Payment" description="Allocate a payment to outstanding dues. Posting and receipt numbering are atomic." /><Card><CardContent className="pt-6"><form className="space-y-5" onSubmit={submit}><div className="grid gap-4 md:grid-cols-3"><label className="grid gap-2 text-sm">Student<select className={select} value={studentId} onChange={(e)=>setStudent(e.target.value)}>{students.map((x)=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label className="grid gap-2 text-sm">Academic Year<select className={select} value={yearId} onChange={(e)=>setYear(e.target.value)}>{years.map((x)=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label className="grid gap-2 text-sm">Payment Mode<select className={select} value={modeId} onChange={(e)=>setMode(e.target.value)}>{modes.map((x)=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label></div>{eligible.map((x)=><label key={x.id} className="grid gap-2 rounded-2xl border p-4 text-sm md:grid-cols-[1fr_12rem] md:items-center"><span>{x.feeHeadName}<span className="block text-muted-foreground">Outstanding {money.format(x.outstanding)}</span></span><Input aria-label={`Payment toward ${x.feeHeadName}`} type="number" min="0" max={x.outstanding} step="0.01" value={amounts[x.id]??""} onChange={(e)=>setAmounts((old)=>({...old,[x.id]:e.target.value}))}/></label>)}<div className="flex items-center justify-between"><strong>Total {money.format(total)}</strong><Button disabled={pending||total<=0}>{pending?"Posting…":"Post Payment"}</Button></div></form></CardContent></Card><Toaster /></div> }

export function PaymentsManager({ payments }: { payments: FeePayment[] }) { const [pending,start]=useTransition(); const router=useRouter(); return <div className="space-y-6"><PageHeader title="Payments" description="Immutable receipt history with controlled reversals." /><Card><CardContent className="pt-6"><div className="overflow-x-auto"><Table><TableHeader><TableRow><TableHead>Receipt</TableHead><TableHead>Student</TableHead><TableHead>Date</TableHead><TableHead>Mode</TableHead><TableHead>Amount</TableHead><TableHead>Status</TableHead><TableHead>Action</TableHead></TableRow></TableHeader><TableBody>{payments.map((x)=><TableRow key={x.id}><TableCell><Link className="font-medium underline-offset-4 hover:underline" href={`/fees/receipts/${x.id}`}>{x.receiptNo}</Link></TableCell><TableCell>{x.studentName}</TableCell><TableCell>{date.format(new Date(x.paymentDate))}</TableCell><TableCell>{x.paymentModeName}</TableCell><TableCell>{money.format(x.amount)}</TableCell><TableCell><Badge>{x.status}</Badge></TableCell><TableCell>{x.status==="posted"?<Button size="sm" variant="outline" disabled={pending} onClick={()=>{const reason=window.prompt("Enter reversal reason");if(reason)start(async()=>{const r=await reverseFeePayment({paymentId:x.id,reason});notify(r);if(r.status==="success")router.refresh();});}}><RotateCcw/>Reverse</Button>:x.reversalReason}</TableCell></TableRow>)}</TableBody></Table></div></CardContent></Card><Toaster /></div> }

export function FeeSettingsManager({ settings }: { settings: FeeSettings }) { const [value,setValue]=useState(settings);const [pending,start]=useTransition();return <div className="space-y-6"><PageHeader title="Fee Communication Settings" description="Configure queueing rules. Automatic execution requires a separately configured scheduler."/><Card><CardContent className="space-y-5 pt-6"><label className="flex gap-3"><input type="checkbox" checked={value.whatsappFeeRemindersEnabled} onChange={(e)=>setValue({...value,whatsappFeeRemindersEnabled:e.target.checked})}/>Enable overdue reminder queueing</label><label className="flex gap-3"><input type="checkbox" checked={value.whatsappPaymentConfirmationsEnabled} onChange={(e)=>setValue({...value,whatsappPaymentConfirmationsEnabled:e.target.checked})}/>Queue payment confirmations</label><div className="grid gap-4 md:grid-cols-3"><label className="grid gap-2 text-sm">Days after due<Input type="number" value={value.reminderAfterDueDays} onChange={(e)=>setValue({...value,reminderAfterDueDays:Number(e.target.value)})}/></label><label className="grid gap-2 text-sm">Repeat every days<Input type="number" value={value.repeatEveryDays??""} onChange={(e)=>setValue({...value,repeatEveryDays:e.target.value?Number(e.target.value):null})}/></label><label className="grid gap-2 text-sm">Max reminders<Input type="number" value={value.maxRemindersPerDue??""} onChange={(e)=>setValue({...value,maxRemindersPerDue:e.target.value?Number(e.target.value):null})}/></label></div><div className="flex flex-wrap gap-3"><Button disabled={pending} onClick={()=>start(async()=>notify(await updateFeeSettings(value)))}>Save Settings</Button><Button variant="outline" disabled={pending} onClick={()=>start(async()=>notify(await queueOverdueFeeReminders()))}>Run Reminder Queue Now</Button></div><p className="text-sm text-muted-foreground">Live Meta delivery is unavailable until credentials and approved templates are configured.</p></CardContent></Card><Toaster/></div> }

export function MessagesManager({ messages }: { messages: FeeMessage[] }) { return <div className="space-y-6"><PageHeader title="WhatsApp Outbox" description="Audit queued payment confirmations and overdue reminders independently from accounting."/><Card><CardContent className="pt-6"><div className="overflow-x-auto"><Table><TableHeader><TableRow><TableHead>Student</TableHead><TableHead>Message</TableHead><TableHead>Recipient</TableHead><TableHead>Status</TableHead><TableHead>Attempts</TableHead><TableHead>Created</TableHead></TableRow></TableHeader><TableBody>{messages.map((x)=><TableRow key={x.id}><TableCell>{x.studentName}</TableCell><TableCell>{x.messageType.replaceAll("_"," ")}</TableCell><TableCell>{x.recipientType} · {x.recipientPhone.slice(-4).padStart(x.recipientPhone.length,"•")}</TableCell><TableCell><Badge>{x.status}</Badge>{x.lastErrorCode?<span className="block text-xs text-muted-foreground">{x.lastErrorCode}</span>:null}</TableCell><TableCell>{x.attemptCount}</TableCell><TableCell>{date.format(new Date(x.createdAt))}</TableCell></TableRow>)}{messages.length===0?<TableRow><TableCell colSpan={6} className="py-10 text-center text-muted-foreground">No queued messages yet.</TableCell></TableRow>:null}</TableBody></Table></div></CardContent></Card></div> }

function StudentPaymentsTable({ payments }: { payments: FeePayment[] }) {
  return <Card><CardContent className="pt-6"><div className="overflow-x-auto"><Table><TableHeader><TableRow><TableHead>Receipt</TableHead><TableHead>Date</TableHead><TableHead>Mode</TableHead><TableHead>Amount</TableHead><TableHead>Status</TableHead></TableRow></TableHeader><TableBody>{payments.map((payment) => <TableRow key={payment.id}><TableCell><Link className="font-medium underline-offset-4 hover:underline" href={`/fees/receipts/${payment.id}`}>{payment.receiptNo}</Link></TableCell><TableCell>{date.format(new Date(payment.paymentDate))}</TableCell><TableCell>{payment.paymentModeName}</TableCell><TableCell>{money.format(payment.amount)}</TableCell><TableCell><Badge>{payment.status}</Badge></TableCell></TableRow>)}{payments.length === 0 ? <TableRow><TableCell colSpan={5} className="py-10 text-center text-muted-foreground">No payment receipts yet.</TableCell></TableRow> : null}</TableBody></Table></div></CardContent></Card>;
}

export function StudentFeePortal({ dues, payments }: { dues: FeeDue[]; payments: FeePayment[] }) { const outstanding=dues.reduce((sum,x)=>sum+x.outstanding,0);return <div className="space-y-6"><PageHeader title="My Fees" description="Review your fee dues and payment receipts."/><div className="grid gap-4 sm:grid-cols-2"><StatCard title="Outstanding" value={money.format(outstanding)} icon={IndianRupee}/><StatCard title="Payments" value={String(payments.filter((x)=>x.status==="posted").length)} icon={ReceiptText}/></div><DuesTable dues={dues}/><StudentPaymentsTable payments={payments}/></div> }
