"use client";

import Link from "next/link";
import { useMemo, useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { Banknote, Bell, CreditCard, Download, IndianRupee, Printer, QrCode, ReceiptText, RotateCcw, Send } from "lucide-react";

import { StatCard } from "@/components/dashboard/stat-card";
import { PageHeader } from "@/components/layout/page-header";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Toaster, toast } from "@/components/ui/toast";
import { createFeeAssignment, postFeePayment, queueManualFeeReminder, queueOverdueFeeReminders, reverseFeePayment, updateFeeSettings } from "@/features/fees/actions/fee-actions";
import type { FeeDue, FeeMessage, FeeOption, FeePayment, FeeSettings, FeeStudent, FeeSummary } from "@/features/fees/types/fees";

const money = new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR" });
const date = new Intl.DateTimeFormat("en-IN", { dateStyle: "medium" });
const month = new Intl.DateTimeFormat("en-IN", { month: "short", year: "numeric" });
const select = "h-10 w-full rounded-2xl border border-input bg-background px-3 text-sm";
function notify(result: { status: string; message: string }) { toast.add({ title: result.status === "success" ? "Success" : "Unable to continue", description: result.message, type: result.status === "success" ? "success" : "error" }); }
function safeDate(value: string) { return new Date(value.includes("T") ? value : `${value}T00:00:00`); }

function downloadCsv(filename: string, rows: Array<Array<string | number>>) {
  const csv = rows.map((row) => row.map((cell) => `"${String(cell).replaceAll('"', '""')}"`).join(",")).join("\n");
  const url = URL.createObjectURL(new Blob([csv], { type: "text/csv;charset=utf-8" }));
  const link = document.createElement("a"); link.href = url; link.download = filename; link.click(); URL.revokeObjectURL(url);
}

export function FeesOverview({ summary }: { summary: FeeSummary }) {
  return <div className="space-y-6"><PageHeader title="Fees" description="Manage student fees, collections, receipts, pending fees, reports, and communication." icon={IndianRupee} theme="fee-heads" />
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard title="Pending Fees" value={money.format(summary.totalOutstanding)} description="Across active dues" icon={IndianRupee} tone="rose" href="/fees/student-fees" linkLabel="View pending fees" /><StatCard title="Collected Today" value={money.format(summary.collectionsToday)} description="Posted payments" icon={CreditCard} tone="emerald" href="/fees/payments" linkLabel="View payments" /><StatCard title="This Month" value={money.format(summary.collectionsThisMonth)} description="Posted collections" icon={ReceiptText} tone="blue" href="/fees/reports" linkLabel="View reports" /><StatCard title="Pending Due Items" value={String(summary.overdueCount)} description="Need follow-up" icon={Bell} tone="amber" href="/fees/student-fees" linkLabel="Review" /></div>
    <div className="grid gap-4 md:grid-cols-3">{[["Pending Fees","Assign fees and review pending balances.","/fees/student-fees"],["Collect Payment","Record a payment and issue a receipt.","/fees/collect"],["Reports & Ledger","Review collections, pending fees and student ledgers.","/fees/reports"]].map(([title,description,href]) => <Card key={href}><CardHeader><CardTitle>{title}</CardTitle></CardHeader><CardContent><p className="mb-4 text-sm text-muted-foreground">{description}</p><Button nativeButton={false} render={<Link href={href} />}>Open</Button></CardContent></Card>)}</div></div>;
}

export function StudentFeesManager({ students, years, heads, dues }: { students: FeeStudent[]; years: FeeOption[]; heads: FeeOption[]; dues: FeeDue[] }) {
  const [pending, start] = useTransition(); const router = useRouter(); const [studentId, setStudent] = useState(students[0]?.id ?? ""); const [yearId, setYear] = useState(years.find((year) => year.isCurrent)?.id ?? years[0]?.id ?? ""); const [headId, setHead] = useState(heads[0]?.id ?? ""); const [amount, setAmount] = useState(""); const [dueDate, setDueDate] = useState(new Date().toISOString().slice(0,10));
  function submit(e: React.FormEvent) { e.preventDefault(); const gross = Number(amount); start(async () => { const result = await createFeeAssignment({ studentId, academicYearId: yearId, feeHeadId: headId, amount: gross, discountType: null, discountValue: 0, effectiveFrom: dueDate, effectiveTo: null, installments: [{ installmentNo: 1, dueDate, grossAmount: gross, discountAmount: 0, netAmount: gross }] }); notify(result); if (result.status === "success") { setAmount(""); router.refresh(); } }); }
  return <div className="space-y-6"><PageHeader title="Pending Fees" description="Assign a fee and track each student's paid and pending balance. Discounts and installment entry are not used." icon={IndianRupee} theme="fee-heads" />
    <Card><CardHeader><CardTitle>Assign Fee</CardTitle></CardHeader><CardContent><form className="grid gap-4 md:grid-cols-5" onSubmit={submit}><label className="grid gap-2 text-sm">Student<select className={select} value={studentId} onChange={(e)=>setStudent(e.target.value)} required>{students.map((x)=><option key={x.id} value={x.id}>{x.name}{x.admissionNo ? ` · ${x.admissionNo}`:""}</option>)}</select></label><label className="grid gap-2 text-sm">Academic Year<select className={select} value={yearId} onChange={(e)=>setYear(e.target.value)} required>{years.map((x)=><option key={x.id} value={x.id}>{x.name}{x.isCurrent?" (Current)":""}</option>)}</select></label><label className="grid gap-2 text-sm">Fee Head<select className={select} value={headId} onChange={(e)=>setHead(e.target.value)} required>{heads.map((x)=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label className="grid gap-2 text-sm">Amount<Input type="number" min="0.01" step="0.01" value={amount} onChange={(e)=>setAmount(e.target.value)} required /></label><label className="grid gap-2 text-sm">Due Date<Input type="date" value={dueDate} onChange={(e)=>setDueDate(e.target.value)} required /></label><Button className="md:col-span-5 md:justify-self-end" disabled={pending}>{pending ? "Assigning…":"Assign Fee"}</Button></form></CardContent></Card>
    <DuesTable dues={dues} reminders /><Toaster /></div>;
}

function DuesTable({ dues, reminders=false }: { dues: FeeDue[]; reminders?: boolean }) { const [pending,start]=useTransition(); return <Card><CardContent className="pt-6"><div className="overflow-x-auto"><Table><TableHeader><TableRow><TableHead>Student</TableHead><TableHead>Fee Head</TableHead><TableHead>Academic Year</TableHead><TableHead>Due Date</TableHead><TableHead>Pending</TableHead><TableHead>Status</TableHead>{reminders?<TableHead>Action</TableHead>:null}</TableRow></TableHeader><TableBody>{dues.map((x)=><TableRow key={x.id}><TableCell>{x.studentName}<span className="block text-xs text-muted-foreground">{x.admissionNo}</span></TableCell><TableCell>{x.feeHeadName}</TableCell><TableCell>{x.academicYearName}</TableCell><TableCell>{date.format(safeDate(x.dueDate))}</TableCell><TableCell>{money.format(x.outstanding)}</TableCell><TableCell><Badge variant={x.outstanding > 0 ? "outline":"secondary"}>{x.outstanding > 0 ? "Pending" : "Paid"}</Badge></TableCell>{reminders?<TableCell><Button size="sm" variant="outline" disabled={pending || x.outstanding <= 0} onClick={()=>start(async()=>notify(await queueManualFeeReminder({dueId:x.id})))}><Send /> Remind</Button></TableCell>:null}</TableRow>)}{dues.length===0?<TableRow><TableCell colSpan={reminders?7:6} className="py-10 text-center text-muted-foreground">No fee dues yet.</TableCell></TableRow>:null}</TableBody></Table></div></CardContent></Card> }

export function PaymentDetailsCard({ settings, title="Payment Details" }: { settings: FeeSettings; title?: string }) {
  const hasBank = settings.bankName || settings.bankAccountName || settings.bankAccountNumber || settings.bankIfsc || settings.bankBranch;
  const hasDetails = settings.qrCodeUrl || settings.upiId || hasBank;
  return <Card><CardHeader><CardTitle className="flex items-center gap-2"><Banknote className="size-5" />{title}</CardTitle></CardHeader><CardContent>{hasDetails?<div className="grid gap-6 md:grid-cols-[220px_1fr]">
    <div className="flex min-h-52 items-center justify-center rounded-2xl border bg-muted/30 p-4">{settings.qrCodeUrl?<img src={settings.qrCodeUrl} alt="Fee payment QR code" className="max-h-48 max-w-48 object-contain" />:<div className="text-center text-sm text-muted-foreground"><QrCode className="mx-auto mb-2 size-10"/>QR code not configured</div>}</div>
    <div className="grid gap-4 sm:grid-cols-2"><div className="rounded-2xl border p-4"><p className="text-xs font-medium uppercase tracking-wide text-muted-foreground">UPI ID</p><p className="mt-2 font-semibold break-all">{settings.upiId || "Not configured"}</p></div><div className="rounded-2xl border p-4"><p className="text-xs font-medium uppercase tracking-wide text-muted-foreground">Bank</p><p className="mt-2 font-semibold">{settings.bankName || "Not configured"}</p>{settings.bankBranch?<p className="text-sm text-muted-foreground">{settings.bankBranch}</p>:null}</div><div className="rounded-2xl border p-4"><p className="text-xs font-medium uppercase tracking-wide text-muted-foreground">Account Name</p><p className="mt-2 font-semibold">{settings.bankAccountName || "—"}</p></div><div className="rounded-2xl border p-4"><p className="text-xs font-medium uppercase tracking-wide text-muted-foreground">Account Number / IFSC</p><p className="mt-2 font-semibold break-all">{settings.bankAccountNumber || "—"}</p><p className="text-sm text-muted-foreground">IFSC: {settings.bankIfsc || "—"}</p></div></div>
  </div>:<p className="text-sm text-muted-foreground">Payment details have not been configured by the institute yet.</p>}</CardContent></Card>;
}

export function CollectPayment({ students, years, modes, dues, settings }: { students: FeeStudent[]; years: FeeOption[]; modes: FeeOption[]; dues: FeeDue[]; settings: FeeSettings }) {
  const [pending,start]=useTransition(); const router=useRouter(); const [studentId,setStudent]=useState(students[0]?.id??""); const [yearId,setYear]=useState(years.find((year)=>year.isCurrent)?.id??years[0]?.id??""); const [modeId,setMode]=useState(modes[0]?.id??""); const [paymentDate,setPaymentDate]=useState(new Date().toISOString().slice(0,10)); const [referenceNo,setReferenceNo]=useState(""); const [remarks,setRemarks]=useState(""); const [amounts,setAmounts]=useState<Record<string,string>>({}); const eligible=useMemo(()=>dues.filter((x)=>x.studentId===studentId&&x.academicYearId===yearId&&x.outstanding>0),[dues,studentId,yearId]); const total=eligible.reduce((sum,x)=>sum+Number(amounts[x.id]??0),0);
  function submit(e:React.FormEvent){e.preventDefault(); start(async()=>{const result=await postFeePayment({studentId,academicYearId:yearId,paymentModeId:modeId,paymentDate:new Date(`${paymentDate}T12:00:00`).toISOString(),referenceNo:referenceNo||null,remarks:remarks||null,allocations:eligible.map((x)=>({dueId:x.id,amount:Number(amounts[x.id]??0)})).filter((x)=>x.amount>0)});notify(result);if(result.status==="success"){setAmounts({});setReferenceNo("");setRemarks("");router.refresh();}})}
  return <div className="space-y-6"><PageHeader title="Collect Payment" description="Use the institute QR/UPI/bank details and record the payment received. Transaction/reference number is optional." /><PaymentDetailsCard settings={settings}/><Card><CardHeader><CardTitle>Record Payment</CardTitle></CardHeader><CardContent><form className="space-y-5" onSubmit={submit}><div className="grid gap-4 md:grid-cols-3"><label className="grid gap-2 text-sm">Student<select className={select} value={studentId} onChange={(e)=>setStudent(e.target.value)} required>{students.map((x)=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label className="grid gap-2 text-sm">Academic Year<select className={select} value={yearId} onChange={(e)=>setYear(e.target.value)} required>{years.map((x)=><option key={x.id} value={x.id}>{x.name}{x.isCurrent?" (Current)":""}</option>)}</select></label><label className="grid gap-2 text-sm">Payment Mode<select className={select} value={modeId} onChange={(e)=>setMode(e.target.value)} required>{modes.map((x)=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label className="grid gap-2 text-sm">Payment Date<Input type="date" value={paymentDate} onChange={(e)=>setPaymentDate(e.target.value)} required /></label><label className="grid gap-2 text-sm">Reference / Transaction No. <span className="text-xs text-muted-foreground">Optional</span><Input value={referenceNo} onChange={(e)=>setReferenceNo(e.target.value)} /></label><label className="grid gap-2 text-sm">Remarks <span className="text-xs text-muted-foreground">Optional</span><Input value={remarks} onChange={(e)=>setRemarks(e.target.value)} /></label></div>{eligible.map((x)=><label key={x.id} className="grid gap-2 rounded-2xl border p-4 text-sm md:grid-cols-[1fr_12rem] md:items-center"><span>{x.feeHeadName}<span className="block text-muted-foreground">Pending {money.format(x.outstanding)} · {date.format(safeDate(x.dueDate))}</span></span><Input aria-label={`Payment toward ${x.feeHeadName}`} type="number" min="0" max={x.outstanding} step="0.01" value={amounts[x.id]??""} onChange={(e)=>setAmounts((old)=>({...old,[x.id]:e.target.value}))}/></label>)}{eligible.length===0?<p className="rounded-2xl border p-4 text-sm text-muted-foreground">No pending fees for the selected student and academic year.</p>:null}<div className="flex items-center justify-between"><strong>Total {money.format(total)}</strong><Button disabled={pending||total<=0}>{pending?"Posting…":"Post Payment"}</Button></div></form></CardContent></Card><Toaster /></div>;
}

export function PaymentsManager({ payments }: { payments: FeePayment[] }) { const [pending,start]=useTransition(); const router=useRouter(); return <div className="space-y-6"><PageHeader title="Payments" description="Receipt history with controlled reversals. Reference/transaction numbers are optional." /><Card><CardContent className="pt-6"><div className="overflow-x-auto"><Table><TableHeader><TableRow><TableHead>Receipt</TableHead><TableHead>Student</TableHead><TableHead>Date</TableHead><TableHead>Mode</TableHead><TableHead>Reference</TableHead><TableHead>Amount</TableHead><TableHead>Status</TableHead><TableHead>Action</TableHead></TableRow></TableHeader><TableBody>{payments.map((x)=><TableRow key={x.id}><TableCell><Link className="font-medium underline-offset-4 hover:underline" href={`/fees/receipts/${x.id}`}>{x.receiptNo}</Link></TableCell><TableCell>{x.studentName}</TableCell><TableCell>{date.format(new Date(x.paymentDate))}</TableCell><TableCell>{x.paymentModeName}</TableCell><TableCell>{x.referenceNo || "—"}</TableCell><TableCell>{money.format(x.amount)}</TableCell><TableCell><Badge>{x.status}</Badge></TableCell><TableCell>{x.status==="posted"?<Button size="sm" variant="outline" disabled={pending} onClick={()=>{const reason=window.prompt("Enter reversal reason");if(reason)start(async()=>{const r=await reverseFeePayment({paymentId:x.id,reason});notify(r);if(r.status==="success")router.refresh();});}}><RotateCcw/>Reverse</Button>:x.reversalReason}</TableCell></TableRow>)}</TableBody></Table></div></CardContent></Card><Toaster /></div> }

export function FeeSettingsManager({ settings }: { settings: FeeSettings }) {
  const [value,setValue]=useState(settings); const [pending,start]=useTransition();
  return <div className="space-y-6"><PageHeader title="Fee Settings" description="Configure institute QR/UPI/bank payment details and fee reminder rules."/>
    <Card><CardHeader><CardTitle>Institute Payment Details</CardTitle></CardHeader><CardContent className="grid gap-4 md:grid-cols-2"><label className="grid gap-2 text-sm">UPI ID<Input value={value.upiId??""} onChange={(e)=>setValue({...value,upiId:e.target.value||null})}/></label><label className="grid gap-2 text-sm">QR Code Image URL<Input placeholder="https://... or data:image/..." value={value.qrCodeUrl??""} onChange={(e)=>setValue({...value,qrCodeUrl:e.target.value||null})}/></label><label className="grid gap-2 text-sm">Bank Name<Input value={value.bankName??""} onChange={(e)=>setValue({...value,bankName:e.target.value||null})}/></label><label className="grid gap-2 text-sm">Account Name<Input value={value.bankAccountName??""} onChange={(e)=>setValue({...value,bankAccountName:e.target.value||null})}/></label><label className="grid gap-2 text-sm">Account Number<Input value={value.bankAccountNumber??""} onChange={(e)=>setValue({...value,bankAccountNumber:e.target.value||null})}/></label><label className="grid gap-2 text-sm">IFSC<Input value={value.bankIfsc??""} onChange={(e)=>setValue({...value,bankIfsc:e.target.value||null})}/></label><label className="grid gap-2 text-sm">Bank Branch<Input value={value.bankBranch??""} onChange={(e)=>setValue({...value,bankBranch:e.target.value||null})}/></label><label className="grid gap-2 text-sm">Monthly Due Day<Input type="number" min="1" max="28" value={value.defaultMonthlyDueDay} onChange={(e)=>setValue({...value,defaultMonthlyDueDay:Number(e.target.value)})}/></label></CardContent></Card>
    <PaymentDetailsCard settings={value} title="Parent/Student Payment Preview"/>
    <Card><CardHeader><CardTitle>Reminder Settings</CardTitle></CardHeader><CardContent className="space-y-5"><label className="flex gap-3"><input type="checkbox" checked={value.whatsappFeeRemindersEnabled} onChange={(e)=>setValue({...value,whatsappFeeRemindersEnabled:e.target.checked})}/>Enable pending-fee reminder queueing</label><label className="flex gap-3"><input type="checkbox" checked={value.whatsappPaymentConfirmationsEnabled} onChange={(e)=>setValue({...value,whatsappPaymentConfirmationsEnabled:e.target.checked})}/>Queue payment confirmations</label><div className="grid gap-4 md:grid-cols-3"><label className="grid gap-2 text-sm">Days after due<Input type="number" value={value.reminderAfterDueDays} onChange={(e)=>setValue({...value,reminderAfterDueDays:Number(e.target.value)})}/></label><label className="grid gap-2 text-sm">Repeat every days<Input type="number" value={value.repeatEveryDays??""} onChange={(e)=>setValue({...value,repeatEveryDays:e.target.value?Number(e.target.value):null})}/></label><label className="grid gap-2 text-sm">Max reminders<Input type="number" value={value.maxRemindersPerDue??""} onChange={(e)=>setValue({...value,maxRemindersPerDue:e.target.value?Number(e.target.value):null})}/></label></div></CardContent></Card>
    <div className="flex flex-wrap gap-3"><Button disabled={pending} onClick={()=>start(async()=>notify(await updateFeeSettings(value)))}>Save Settings</Button><Button variant="outline" disabled={pending} onClick={()=>start(async()=>notify(await queueOverdueFeeReminders()))}>Run Reminder Queue Now</Button></div><Toaster/></div>;
}

export function MessagesManager({ messages }: { messages: FeeMessage[] }) { return <div className="space-y-6"><PageHeader title="WhatsApp Outbox" description="Audit queued payment confirmations and pending-fee reminders independently from accounting."/><Card><CardContent className="pt-6"><div className="overflow-x-auto"><Table><TableHeader><TableRow><TableHead>Student</TableHead><TableHead>Message</TableHead><TableHead>Recipient</TableHead><TableHead>Status</TableHead><TableHead>Attempts</TableHead><TableHead>Created</TableHead></TableRow></TableHeader><TableBody>{messages.map((x)=><TableRow key={x.id}><TableCell>{x.studentName}</TableCell><TableCell>{x.messageType.replaceAll("_"," ")}</TableCell><TableCell>{x.recipientType} · {x.recipientPhone.slice(-4).padStart(x.recipientPhone.length,"•")}</TableCell><TableCell><Badge>{x.status}</Badge>{x.lastErrorCode?<span className="block text-xs text-muted-foreground">{x.lastErrorCode}</span>:null}</TableCell><TableCell>{x.attemptCount}</TableCell><TableCell>{date.format(new Date(x.createdAt))}</TableCell></TableRow>)}{messages.length===0?<TableRow><TableCell colSpan={6} className="py-10 text-center text-muted-foreground">No queued messages yet.</TableCell></TableRow>:null}</TableBody></Table></div></CardContent></Card></div> }

function StudentPaymentsTable({ payments }: { payments: FeePayment[] }) {
  return <Card><CardHeader><CardTitle>Payment History</CardTitle></CardHeader><CardContent><div className="overflow-x-auto"><Table><TableHeader><TableRow><TableHead>Receipt</TableHead><TableHead>Date</TableHead><TableHead>Mode</TableHead><TableHead>Amount</TableHead><TableHead>Status</TableHead></TableRow></TableHeader><TableBody>{payments.map((payment) => <TableRow key={payment.id}><TableCell><Link className="font-medium underline-offset-4 hover:underline" href={`/fees/receipts/${payment.id}`}>{payment.receiptNo}</Link></TableCell><TableCell>{date.format(new Date(payment.paymentDate))}</TableCell><TableCell>{payment.paymentModeName}</TableCell><TableCell>{money.format(payment.amount)}</TableCell><TableCell><Badge>{payment.status}</Badge></TableCell></TableRow>)}{payments.length === 0 ? <TableRow><TableCell colSpan={5} className="py-10 text-center text-muted-foreground">No payment receipts yet.</TableCell></TableRow> : null}</TableBody></Table></div></CardContent></Card>;
}

function MonthlyFeesBoard({ dues }: { dues: FeeDue[] }) {
  const rows = useMemo(() => {
    const map = new Map<string, { key:string; studentName:string; academicYearName:string; dueDate:string; total:number; pending:number }>();
    for (const due of dues.filter((item) => item.scheduleType === "monthly")) {
      const d = safeDate(due.dueDate); const monthKey = `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}`; const key = `${due.studentId}:${due.academicYearId}:${monthKey}`; const current = map.get(key) ?? { key, studentName: due.studentName, academicYearName: due.academicYearName, dueDate: due.dueDate, total: 0, pending: 0 }; current.total += due.netAmount; current.pending += due.outstanding; map.set(key,current);
    }
    return [...map.values()].sort((a,b)=>a.dueDate.localeCompare(b.dueDate));
  }, [dues]);
  return <Card><CardHeader><CardTitle>Monthly Fees Paid Board</CardTitle></CardHeader><CardContent>{rows.length?<div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{rows.map((row)=><div key={row.key} className="rounded-2xl border p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-semibold">{month.format(safeDate(row.dueDate))}</p><p className="text-xs text-muted-foreground">{row.studentName} · {row.academicYearName}</p></div><Badge variant={row.pending > 0 ? "outline":"secondary"}>{row.pending > 0 ? "Pending":"Paid"}</Badge></div><p className="mt-4 text-sm">Monthly Fee <strong>{money.format(row.total)}</strong></p><p className="text-sm text-muted-foreground">{row.pending > 0 ? `Pending ${money.format(row.pending)}` : "Paid in full"}</p></div>)}</div>:<p className="text-sm text-muted-foreground">No monthly fee schedule is available yet.</p>}</CardContent></Card>;
}

export function StudentFeePortal({ dues, payments, settings, isParent=false }: { dues: FeeDue[]; payments: FeePayment[]; settings?: FeeSettings; isParent?: boolean }) {
  const outstanding=dues.reduce((sum,x)=>sum+x.outstanding,0); const paid=payments.filter((x)=>x.status==="posted").reduce((sum,x)=>sum+x.amount,0);
  return <div className="space-y-6"><PageHeader title={isParent?"Fees":"My Fees"} description={isParent?"View payment details, monthly fee status, pending fees and receipts for your child.":"Review fee dues and payment receipts."}/><div className="grid gap-4 sm:grid-cols-3"><StatCard title="Pending Fees" value={money.format(outstanding)} icon={IndianRupee}/><StatCard title="Total Paid" value={money.format(paid)} icon={CreditCard}/><StatCard title="Receipts" value={String(payments.filter((x)=>x.status==="posted").length)} icon={ReceiptText}/></div>{settings?<PaymentDetailsCard settings={settings}/>:null}<MonthlyFeesBoard dues={dues}/><DuesTable dues={dues.filter((x)=>x.outstanding>0)}/><StudentPaymentsTable payments={payments}/></div>;
}

export function FeeReports({ students, years, dues, payments }: { students: FeeStudent[]; years: FeeOption[]; dues: FeeDue[]; payments: FeePayment[] }) {
  const [studentId,setStudentId]=useState(""); const [yearId,setYearId]=useState(years.find((year)=>year.isCurrent)?.id??years[0]?.id??""); const [from,setFrom]=useState(""); const [to,setTo]=useState("");
  const filteredDues=useMemo(()=>dues.filter((x)=>(!studentId||x.studentId===studentId)&&(!yearId||x.academicYearId===yearId)&&(!from||x.dueDate>=from)&&(!to||x.dueDate<=to)),[dues,studentId,yearId,from,to]);
  const filteredPayments=useMemo(()=>payments.filter((x)=>(!studentId||x.studentId===studentId)&&(!yearId||x.academicYearId===yearId)&&(!from||x.paymentDate.slice(0,10)>=from)&&(!to||x.paymentDate.slice(0,10)<=to)),[payments,studentId,yearId,from,to]);
  const pending=filteredDues.reduce((sum,x)=>sum+x.outstanding,0); const collected=filteredPayments.filter((x)=>x.status==="posted").reduce((sum,x)=>sum+x.amount,0);
  const headSummary=useMemo(()=>{const map=new Map<string,{total:number;pending:number}>();for(const d of filteredDues){const v=map.get(d.feeHeadName)??{total:0,pending:0};v.total+=d.netAmount;v.pending+=d.outstanding;map.set(d.feeHeadName,v)}return [...map.entries()].sort((a,b)=>a[0].localeCompare(b[0]));},[filteredDues]);
  const modeSummary=useMemo(()=>{const map=new Map<string,number>();for(const p of filteredPayments.filter((x)=>x.status==="posted"))map.set(p.paymentModeName,(map.get(p.paymentModeName)??0)+p.amount);return [...map.entries()].sort((a,b)=>a[0].localeCompare(b[0]));},[filteredPayments]);
  const exportPending=()=>downloadCsv("pending-fees.csv",[["Student","Admission No","Academic Year","Fee Head","Due Date","Amount","Pending"],...filteredDues.filter((x)=>x.outstanding>0).map((x)=>[x.studentName,x.admissionNo??"",x.academicYearName,x.feeHeadName,x.dueDate,x.netAmount,x.outstanding])]);
  const exportCollections=()=>downloadCsv("fee-collections.csv",[["Receipt","Student","Academic Year","Date","Mode","Reference","Amount","Status"],...filteredPayments.map((x)=>[x.receiptNo,x.studentName,x.academicYearName,x.paymentDate,x.paymentModeName,x.referenceNo??"",x.amount,x.status])]);
  return <div className="space-y-6"><PageHeader title="Fee Reports & Ledger" description="Pending Fees, collection reports, fee-head/payment-mode summaries and student ledger. Use Print to save as PDF."/><Card><CardContent className="grid gap-4 pt-6 md:grid-cols-4"><label className="grid gap-2 text-sm">Student<select className={select} value={studentId} onChange={(e)=>setStudentId(e.target.value)}><option value="">All Students</option>{students.map((x)=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label className="grid gap-2 text-sm">Academic Year<select className={select} value={yearId} onChange={(e)=>setYearId(e.target.value)}><option value="">All Years</option>{years.map((x)=><option key={x.id} value={x.id}>{x.name}{x.isCurrent?" (Current)":""}</option>)}</select></label><label className="grid gap-2 text-sm">From<Input type="date" value={from} onChange={(e)=>setFrom(e.target.value)}/></label><label className="grid gap-2 text-sm">To<Input type="date" value={to} onChange={(e)=>setTo(e.target.value)}/></label></CardContent></Card><div className="grid gap-4 sm:grid-cols-3"><StatCard title="Pending Fees" value={money.format(pending)} icon={IndianRupee}/><StatCard title="Collected" value={money.format(collected)} icon={CreditCard}/><StatCard title="Students" value={String(new Set(filteredDues.map((x)=>x.studentId)).size)} icon={ReceiptText}/></div><div className="flex flex-wrap gap-3 print:hidden"><Button variant="outline" onClick={exportPending}><Download/>Pending Fees CSV</Button><Button variant="outline" onClick={exportCollections}><Download/>Collections CSV</Button><Button variant="outline" onClick={()=>window.print()}><Printer/>Print / Save PDF</Button></div>
    <Card><CardHeader><CardTitle>Pending Fees Report</CardTitle></CardHeader><CardContent><div className="overflow-x-auto"><Table><TableHeader><TableRow><TableHead>Student</TableHead><TableHead>Fee Head</TableHead><TableHead>Due Date</TableHead><TableHead>Amount</TableHead><TableHead>Pending</TableHead></TableRow></TableHeader><TableBody>{filteredDues.filter((x)=>x.outstanding>0).map((x)=><TableRow key={x.id}><TableCell>{x.studentName}</TableCell><TableCell>{x.feeHeadName}</TableCell><TableCell>{date.format(safeDate(x.dueDate))}</TableCell><TableCell>{money.format(x.netAmount)}</TableCell><TableCell>{money.format(x.outstanding)}</TableCell></TableRow>)}</TableBody></Table></div></CardContent></Card>
    <Card><CardHeader><CardTitle>Collection Report</CardTitle></CardHeader><CardContent><div className="overflow-x-auto"><Table><TableHeader><TableRow><TableHead>Receipt</TableHead><TableHead>Student</TableHead><TableHead>Date</TableHead><TableHead>Mode</TableHead><TableHead>Reference</TableHead><TableHead>Amount</TableHead></TableRow></TableHeader><TableBody>{filteredPayments.filter((x)=>x.status==="posted").map((x)=><TableRow key={x.id}><TableCell>{x.receiptNo}</TableCell><TableCell>{x.studentName}</TableCell><TableCell>{date.format(new Date(x.paymentDate))}</TableCell><TableCell>{x.paymentModeName}</TableCell><TableCell>{x.referenceNo||"—"}</TableCell><TableCell>{money.format(x.amount)}</TableCell></TableRow>)}</TableBody></Table></div></CardContent></Card>
    <div className="grid gap-4 lg:grid-cols-2"><Card><CardHeader><CardTitle>Fee Head Summary</CardTitle></CardHeader><CardContent><Table><TableHeader><TableRow><TableHead>Fee Head</TableHead><TableHead>Total</TableHead><TableHead>Pending</TableHead></TableRow></TableHeader><TableBody>{headSummary.map(([name,v])=><TableRow key={name}><TableCell>{name}</TableCell><TableCell>{money.format(v.total)}</TableCell><TableCell>{money.format(v.pending)}</TableCell></TableRow>)}</TableBody></Table></CardContent></Card><Card><CardHeader><CardTitle>Payment Mode Summary</CardTitle></CardHeader><CardContent><Table><TableHeader><TableRow><TableHead>Mode</TableHead><TableHead>Collected</TableHead></TableRow></TableHeader><TableBody>{modeSummary.map(([name,total])=><TableRow key={name}><TableCell>{name}</TableCell><TableCell>{money.format(total)}</TableCell></TableRow>)}</TableBody></Table></CardContent></Card></div>
    {studentId?<Card><CardHeader><CardTitle>Student Fee Ledger</CardTitle></CardHeader><CardContent className="space-y-4"><p className="text-sm text-muted-foreground">Ledger for {students.find((x)=>x.id===studentId)?.name}. Fee charges and payment receipts are shown together below.</p><div className="overflow-x-auto"><Table><TableHeader><TableRow><TableHead>Date</TableHead><TableHead>Entry</TableHead><TableHead>Details</TableHead><TableHead>Charge</TableHead><TableHead>Payment</TableHead></TableRow></TableHeader><TableBody>{[...filteredDues.map((x)=>({key:`d-${x.id}`,when:x.dueDate,entry:"Fee",details:x.feeHeadName,charge:x.netAmount,payment:0})),...filteredPayments.filter((x)=>x.status==="posted").map((x)=>({key:`p-${x.id}`,when:x.paymentDate.slice(0,10),entry:"Payment",details:`${x.receiptNo} · ${x.paymentModeName}`,charge:0,payment:x.amount}))].sort((a,b)=>a.when.localeCompare(b.when)).map((x)=><TableRow key={x.key}><TableCell>{date.format(safeDate(x.when))}</TableCell><TableCell>{x.entry}</TableCell><TableCell>{x.details}</TableCell><TableCell>{x.charge?money.format(x.charge):"—"}</TableCell><TableCell>{x.payment?money.format(x.payment):"—"}</TableCell></TableRow>)}</TableBody></Table></div></CardContent></Card>:null}
  </div>;
}
