"use client";
import {useState,useTransition} from "react";
import {Mail,MessageCircle,Send} from "lucide-react";
import {Button} from "@/components/ui/button";
import {Card,CardContent,CardHeader,CardTitle} from "@/components/ui/card";
import {Toaster,toast} from "@/components/ui/toast";
import {sendVerifiedFeeReceipt} from "@/features/fees/actions/receipt-delivery-actions";
import type {FeePayment} from "@/features/fees/types/fees";
export function ReceiptDeliveryPanel({payments}:{payments:FeePayment[]}){const [id,setId]=useState(payments.find(x=>x.status==="posted")?.id??"");const [pending,start]=useTransition();const current=payments.find(x=>x.id===id);function send(channel:"whatsapp"|"email"|"both"){if(!id)return;start(async()=>{const r=await sendVerifiedFeeReceipt({paymentId:id,channel});toast.add({title:r.status==="success"?"Receipt delivery":"Unable to send",description:r.message,type:r.status==="success"?"success":"error"})})}return <><Card><CardHeader><CardTitle>Verify & Send Receipt</CardTitle></CardHeader><CardContent className="space-y-4"><p className="text-sm text-muted-foreground">Recheck the posted payment first. Receipts are sent only to the linked parent contact.</p><select className="h-10 w-full rounded-xl border bg-background px-3 text-sm" value={id} onChange={e=>setId(e.target.value)}><option value="">Select posted receipt</option>{payments.filter(x=>x.status==="posted").map(x=><option key={x.id} value={x.id}>{x.receiptNo} · {x.studentName} · ₹{x.amount.toFixed(2)}</option>)}</select>{current?<div className="rounded-xl border p-3 text-sm"><b>{current.studentName}</b><span className="block text-muted-foreground">{current.receiptNo} · {current.paymentModeName} · ₹{current.amount.toFixed(2)}</span></div>:null}<div className="flex flex-wrap gap-2"><Button type="button" variant="outline" disabled={pending||!id} onClick={()=>send("whatsapp")}><MessageCircle/>WhatsApp</Button><Button type="button" variant="outline" disabled={pending||!id} onClick={()=>send("email")}><Mail/>Email</Button><Button type="button" disabled={pending||!id} onClick={()=>send("both")}><Send/>Send Both</Button></div></CardContent></Card><Toaster/></>}
