"use server";
import { revalidatePath } from "next/cache";
import { z } from "zod";
import { createTeachingBatch,deleteBatchRecord,replaceBatchTimetable,setBatchStatus } from "@/features/batches/services/batch-service";
import type { BatchActionResult } from "@/features/batches/types/batch";
import { batchIdSchema,batchSchema,batchTimetableSchema } from "@/features/batches/validations/batch-schema";
import { requireRole } from "@/lib/auth/services/auth-service";
import { DASHBOARD_ROLES } from "@/lib/navigation";
const PATH="/masters/batches";
const toggleStatusSchema = z.object({ id: z.string().uuid(), isActive: z.boolean() });
function message(error:unknown):string{const value=error instanceof Error?error.message:"";if(value.includes("BATCH_DUPLICATE_IDENTITY")||value.includes("batches_active_academic_identity_key"))return"A Batch with this academic identity already exists.";if(value.includes("SUBJECT_INVALID"))return"The selected Subject does not belong to this institute.";if(value.includes("EFFECTIVE_FROM_FUTURE"))return"This timetable change requires a future Effective From date.";if(value.includes("REFERENCE")||value.includes("_INVALID"))return"One or more selected academic records are unavailable.";return"We could not save the Batch. Please try again.";}
export async function createBatch(input:unknown,approveOverlap=false):Promise<BatchActionResult>{await requireRole(DASHBOARD_ROLES);const parsed=batchSchema.safeParse(input);if(!parsed.success)return{status:"error",message:"Please correct the highlighted fields.",fieldErrors:parsed.error.flatten().fieldErrors};try{const result=await createTeachingBatch(parsed.data,approveOverlap);if(result.status==="success")revalidatePath(PATH);return result;}catch(error){return{status:"error",message:message(error)};}}
export async function updateBatchTimetable(input:unknown,approveOverlap=false):Promise<BatchActionResult>{await requireRole(DASHBOARD_ROLES);const parsed=batchTimetableSchema.safeParse(input);if(!parsed.success)return{status:"error",message:"Please correct the highlighted fields.",fieldErrors:parsed.error.flatten().fieldErrors};try{const result=await replaceBatchTimetable(parsed.data,approveOverlap);if(result.status==="success")revalidatePath(PATH);return result;}catch(error){return{status:"error",message:message(error)};}}
export async function deleteBatch(input:unknown):Promise<BatchActionResult>{const profile=await requireRole(DASHBOARD_ROLES);const id=batchIdSchema.safeParse(input);if(!id.success)return{status:"error",message:"Batch not found."};try{const deleted=await deleteBatchRecord(profile,id.data);if(!deleted)return{status:"error",message:"Batch not found."};revalidatePath(PATH);return{status:"success",message:"Batch permanently deleted."};}catch(error){return{status:"error",message:(error as {code?:string}).code==="23503"?"This Batch is in use and cannot be deleted.":"We could not delete the Batch."};}}
export async function setBatchStatusAction(input:unknown):Promise<BatchActionResult>{const profile=await requireRole(DASHBOARD_ROLES);const parsed=toggleStatusSchema.safeParse(input);if(!parsed.success)return{status:"error",message:"Batch status could not be updated."};try{const updated=await setBatchStatus(profile,parsed.data.id,parsed.data.isActive);if(!updated)return{status:"error",message:"Batch not found."};revalidatePath(PATH);return{status:"success",message:parsed.data.isActive?"Batch activated." : "Batch deactivated."};}catch(error){return{status:"error",message:(error as {message?:string}).message??"We could not update the Batch status."};}}
