import "server-only";

import type { AuthProfile } from "@/features/auth/types/auth";
import type { CancelEventInput, CompleteEventInput, CreateEventInput, EventOverlapConflict, PlannerFilters, RecurringOccurrenceActionInput, RescheduleEventInput, ScheduleChange, ScheduleEvent } from "@/features/learning-planner/types/learning-planner";
import { createClient } from "@/lib/supabase/server";
import { isWhatsAppConfigured } from "@/features/fees/services/whatsapp-service";
import { sendPlannerClassWhatsApp } from "@/features/learning-planner/services/planner-whatsapp-delivery-service";

interface EventRow { id: string; branch_id: string | null; academic_year_id: string; batch_id: string | null; class_schedule_id: string | null; subject_id: string | null; event_date: string; start_time: string | null; end_time: string | null; schedule_type: ScheduleEvent["scheduleType"]; status: ScheduleEvent["status"]; title: string; description: string | null; room: string | null; original_event_id: string | null; related_event_id: string | null; reschedule_pending: boolean; reschedule_pending_resolved_at: string | null; reschedule_reason: string | null; cancellation_reason: string | null; notification_required: boolean; created_at: string; academic_year: { name: string } | { name: string }[]; batch: { name: string } | { name: string }[] | null; subject: { subject_name: string } | { subject_name: string }[] | null }
const optionalOne = <T>(value: T | T[] | null): T | null => !value ? null : Array.isArray(value) ? value[0] ?? null : value;
function institute(profile: AuthProfile) { if (!profile.instituteId) throw new Error("PLANNER_UNAUTHORIZED"); return profile.instituteId; }
function mapEvent(row: EventRow): ScheduleEvent { return { id: row.id, branchId: row.branch_id, academicYearId: row.academic_year_id, academicYearName: optionalOne(row.academic_year)?.name ?? "", batchId: row.batch_id, batchName: optionalOne(row.batch)?.name ?? null, classScheduleId: row.class_schedule_id, subjectId: row.subject_id, subjectName: optionalOne(row.subject)?.subject_name ?? null, eventDate: row.event_date, startTime: row.start_time?.slice(0, 5) ?? null, endTime: row.end_time?.slice(0, 5) ?? null, scheduleType: row.schedule_type, status: row.status, title: row.title, description: row.description, room: row.room, originalEventId: row.original_event_id, relatedEventId: row.related_event_id, reschedulePending: row.reschedule_pending, reschedulePendingResolvedAt: row.reschedule_pending_resolved_at, rescheduleReason: row.reschedule_reason, cancellationReason: row.cancellation_reason, notificationRequired: row.notification_required, createdAt: row.created_at }; }
export async function listScheduleEvents(profile: AuthProfile, filters: PlannerFilters = {}): Promise<ScheduleEvent[]> { const supabase = await createClient(); let query = supabase.from("schedule_events").select("id,branch_id,academic_year_id,batch_id,class_schedule_id,subject_id,event_date,start_time,end_time,schedule_type,status,title,description,room,original_event_id,related_event_id,reschedule_pending,reschedule_pending_resolved_at,reschedule_reason,cancellation_reason,notification_required,created_at,academic_year:academic_years!schedule_events_academic_year_fkey(name),batch:batches!schedule_events_batch_fkey(name),subject:subjects!schedule_events_subject_fkey(subject_name)").eq("institute_id", institute(profile)).order("event_date").order("start_time"); if (profile.branchId) query = query.eq("branch_id", profile.branchId); if (filters.dateFrom) query = query.gte("event_date", filters.dateFrom); if (filters.dateTo) query = query.lte("event_date", filters.dateTo); if (filters.academicYearId) query = query.eq("academic_year_id", filters.academicYearId); if (filters.batchId) query = query.eq("batch_id", filters.batchId); if (filters.subjectId) query = query.eq("subject_id", filters.subjectId); if (filters.scheduleType) query = query.eq("schedule_type", filters.scheduleType); if (filters.status) query = query.eq("status", filters.status); const { data, error } = await query; if (error) throw error; return (data as unknown as EventRow[]).map(mapEvent); }
type EventMutationResult={status:"success";id:string;whatsappStatus:string}|{status:"conflict";conflicts:EventOverlapConflict[]};
export async function createScheduleEvent(profile: AuthProfile, input: CreateEventInput&{approveOverlap?:boolean;overlapReason?:string}): Promise<EventMutationResult> { institute(profile);const supabase = await createClient(); const { data, error } = await supabase.rpc("create_exceptional_planner_event", { p_input: input,p_approve_overlap:input.approveOverlap??false,p_overlap_reason:input.overlapReason??null }); if (error) throw error; const result=data as {status:"success"|"conflict";id?:string;conflicts?:EventOverlapConflict[]};if(result.status==="conflict")return{status:"conflict",conflicts:result.conflicts??[]};const id=result.id!;let whatsappStatus="not_requested";if(input.whatsappRequested){const queued=await supabase.rpc("queue_planner_whatsapp",{p_event_id:id,p_message_type:input.scheduleType==="extra_class"?"extra_class_scheduled":`${input.scheduleType}_scheduled`});whatsappStatus=queued.error?"queue_failed":isWhatsAppConfigured()?((queued.data as {status?:string})?.status??"queued"):"not_configured";}return{status:"success",id,whatsappStatus}; }
export async function rescheduleScheduleEvent(input: RescheduleEventInput): Promise<EventMutationResult> { const supabase = await createClient(); const { data, error } = await supabase.rpc("reschedule_exceptional_planner_event", { p_event_id: input.eventId, p_new_date: input.newDate, p_new_start_time: input.newStartTime, p_new_end_time: input.newEndTime, p_reason: input.reason,p_approve_overlap:input.approveOverlap??false,p_overlap_reason:input.overlapReason??null }); if (error) throw error;const result=data as {status:"success"|"conflict";id?:string;conflicts?:EventOverlapConflict[]};if(result.status==="conflict")return{status:"conflict",conflicts:result.conflicts??[]};const id=result.id!;let whatsappStatus="not_requested";if(input.whatsappRequested){const delivery=await sendPlannerClassWhatsApp(id,"rescheduled");whatsappStatus=delivery.status==="failed"?"queue_failed":delivery.status;}return{status:"success",id,whatsappStatus}; }
export async function cancelScheduleEvent(input: CancelEventInput): Promise<void> { const supabase = await createClient(); const { error } = await supabase.rpc("cancel_schedule_event", { p_event_id: input.eventId, p_reason: input.reason }); if (error) throw error; }
export async function cancelScheduleEventWithOptions(input:CancelEventInput&{reschedulePending:boolean;whatsappRequested:boolean}):Promise<string>{const supabase=await createClient();const{error}=await supabase.rpc("cancel_planner_event",{p_event_id:input.eventId,p_reason:input.reason,p_reschedule_pending:input.reschedulePending});if(error)throw error;if(!input.whatsappRequested)return"not_requested";const delivery=await sendPlannerClassWhatsApp(input.eventId,input.reschedulePending?"cancelled_reschedule_later":"cancelled");return delivery.status==="failed"?"queue_failed":delivery.status;}
export async function schedulePendingReplacement(input:RescheduleEventInput):Promise<EventMutationResult>{const supabase=await createClient();const{data,error}=await supabase.rpc("schedule_pending_exception_replacement",{p_event_id:input.eventId,p_new_date:input.newDate,p_new_start_time:input.newStartTime,p_new_end_time:input.newEndTime,p_reason:input.reason,p_approve_overlap:input.approveOverlap??false,p_overlap_reason:input.overlapReason??null});if(error)throw error;const result=data as {status:"success"|"conflict";id?:string;conflicts?:EventOverlapConflict[]};if(result.status==="conflict")return{status:"conflict",conflicts:result.conflicts??[]};const id=result.id!;let whatsappStatus="not_requested";if(input.whatsappRequested){const delivery=await sendPlannerClassWhatsApp(id,"rescheduled");whatsappStatus=delivery.status==="failed"?"queue_failed":delivery.status;}return{status:"success",id,whatsappStatus};}
export async function persistRecurringOccurrenceException(input:RecurringOccurrenceActionInput):Promise<EventMutationResult>{const supabase=await createClient();const{data,error}=await supabase.rpc("create_recurring_occurrence_exception",{p_class_schedule_id:input.classScheduleId,p_occurrence_date:input.occurrenceDate,p_action:input.action,p_reason:input.reason,p_reschedule_pending:input.reschedulePending??false,p_new_date:input.newDate??null,p_new_start_time:input.newStartTime??null,p_new_end_time:input.newEndTime??null,p_approve_overlap:input.approveOverlap??false,p_overlap_reason:input.overlapReason??null});if(error)throw error;const result=data as {status:"success"|"conflict";id?:string;conflicts?:EventOverlapConflict[]};if(result.status==="conflict")return{status:"conflict",conflicts:result.conflicts??[]};let whatsappStatus="not_requested";if(input.whatsappRequested){const delivery=await sendPlannerClassWhatsApp(result.id!,input.action==="cancel"?(input.reschedulePending?"cancelled_reschedule_later":"cancelled"):"rescheduled");whatsappStatus=delivery.status==="failed"?"queue_failed":delivery.status;}return{status:"success",id:result.id!,whatsappStatus};}
export async function completeScheduleEvent(input: CompleteEventInput): Promise<void> { const supabase = await createClient(); const { error } = await supabase.rpc("complete_schedule_event", { p_event_id: input.eventId }); if (error) throw error; }
export async function listScheduleChanges(profile: AuthProfile): Promise<ScheduleChange[]> { const supabase = await createClient(); const { data, error } = await supabase.from("schedule_changes").select("id,schedule_event_id,change_type,old_date,old_start_time,old_end_time,new_date,new_start_time,new_end_time,reason,changed_at,event:schedule_events!schedule_changes_event_fkey(title,institute_id),profile:profiles!schedule_changes_changed_by_fkey(name)").eq("event.institute_id", institute(profile)).order("changed_at", { ascending: false }).limit(100); if (error) throw error; return (data ?? []).filter((row) => row.event).map((row) => ({ id: row.id, scheduleEventId: row.schedule_event_id, eventTitle: optionalOne(row.event)?.title ?? "", changeType: row.change_type as ScheduleChange["changeType"], oldDate: row.old_date, oldStartTime: row.old_start_time?.slice(0,5) ?? null, oldEndTime: row.old_end_time?.slice(0,5) ?? null, newDate: row.new_date, newStartTime: row.new_start_time?.slice(0,5) ?? null, newEndTime: row.new_end_time?.slice(0,5) ?? null, reason: row.reason, changedByName: optionalOne(row.profile)?.name ?? "SYSTEM", changedAt: row.changed_at })); }
