import "server-only";

import type { AuthProfile } from "@/features/auth/types/auth";
import { fetchIndiaHolidays } from "@/features/learning-planner/services/india-holiday-provider";
import type { HolidayCalendarData, HolidayImportInput, HolidaySettings, PublicHoliday } from "@/features/learning-planner/types/learning-planner";
import { createClient } from "@/lib/supabase/server";

interface ImportedRow { id:string; branch_id:string|null; provider:string; external_id:string; holiday_date:string; name:string; holiday_scope:"national"|"state"; subdivision_code:string|null; observed_as_holiday:boolean }
function institute(profile: AuthProfile): string { if (!profile.instituteId) throw new Error("PLANNER_UNAUTHORIZED"); return profile.instituteId; }
export async function getHolidaySettings(profile: AuthProfile): Promise<HolidaySettings> { const supabase=await createClient(); const {data,error}=await supabase.from("learning_planner_holiday_settings").select("country_code,state_code,show_national_holidays,show_state_holidays").eq("institute_id",institute(profile)).maybeSingle(); if(error) throw error; return data ? {countryCode:"IN",stateCode:data.state_code,showNationalHolidays:data.show_national_holidays,showStateHolidays:data.show_state_holidays}:{countryCode:"IN",stateCode:null,showNationalHolidays:true,showStateHolidays:false}; }
export async function saveHolidaySettings(profile:AuthProfile,settings:HolidaySettings):Promise<void>{const supabase=await createClient();const {error}=await supabase.from("learning_planner_holiday_settings").upsert({institute_id:institute(profile),country_code:"IN",state_code:settings.stateCode,show_national_holidays:settings.showNationalHolidays,show_state_holidays:settings.showStateHolidays,updated_at:new Date().toISOString()},{onConflict:"institute_id"});if(error)throw error;}
export async function listImportedHolidays(profile:AuthProfile,fromDate:string,toDate:string):Promise<PublicHoliday[]>{const supabase=await createClient();let query=supabase.from("learning_planner_public_holidays").select("id,branch_id,provider,external_id,holiday_date,name,holiday_scope,subdivision_code,observed_as_holiday").eq("institute_id",institute(profile)).gte("holiday_date",fromDate).lte("holiday_date",toDate);if(profile.branchId)query=query.or(`branch_id.is.null,branch_id.eq.${profile.branchId}`);const{data,error}=await query;if(error)throw error;return((data??[])as ImportedRow[]).map(row=>({id:row.id,externalId:row.external_id,provider:row.provider,name:row.name,date:row.holiday_date,scope:row.holiday_scope,subdivisionCode:row.subdivision_code,branchId:row.branch_id,source:"imported",readOnly:false,imported:true,observedAsHoliday:row.observed_as_holiday}));}
export async function getHolidayCalendar(profile:AuthProfile,fromDate:string,toDate:string):Promise<HolidayCalendarData>{const settings=await getHolidaySettings(profile);const imported=await listImportedHolidays(profile,fromDate,toDate);const years:number[]=[];for(let year=Number(fromDate.slice(0,4));year<=Number(toDate.slice(0,4));year++)years.push(year);let external:Awaited<ReturnType<typeof fetchIndiaHolidays>>=[];let providerAvailable=true;try{external=(await Promise.all(years.map(year=>fetchIndiaHolidays(year,settings.stateCode)))).flat();}catch{providerAvailable=false;}const seen=new Set(imported.map(item=>`${item.date}:${item.name}`));const decorations:PublicHoliday[]=external.filter(item=>(item.scope==="national"?settings.showNationalHolidays:settings.showStateHolidays)&&item.date>=fromDate&&item.date<=toDate).filter(item=>!seen.has(`${item.date}:${item.name}`)).map(item=>({id:`external:${item.externalId}`,externalId:item.externalId,provider:item.provider,name:item.name,date:item.date,scope:item.scope,subdivisionCode:item.subdivisionCode,branchId:null,source:"external",readOnly:true,imported:false,observedAsHoliday:null}));return{holidays:[...imported,...decorations].sort((a,b)=>a.date.localeCompare(b.date)||a.name.localeCompare(b.name)),providerAvailable};}
export async function importPublicHoliday(profile:AuthProfile,input:HolidayImportInput):Promise<void>{const supabase=await createClient();const instituteId=institute(profile);if(input.branchId){const{data}=await supabase.from("branches").select("id").eq("id",input.branchId).eq("institute_id",instituteId).maybeSingle();if(!data)throw new Error("PLANNER_BRANCH_INVALID");}const normalized=input.name.trim().replace(/\s+/g," ").toUpperCase();let existing=supabase.from("learning_planner_public_holidays").select("id").eq("institute_id",instituteId).eq("provider",input.provider).eq("external_id",input.externalId);existing=input.branchId?existing.eq("branch_id",input.branchId):existing.is("branch_id",null);const{data:found,error:findError}=await existing.maybeSingle();if(findError)throw findError;const values={branch_id:input.branchId??null,holiday_date:input.date,name:normalized,normalized_name:normalized,holiday_scope:input.scope,subdivision_code:input.scope==="state"?input.subdivisionCode:null,observed_as_holiday:input.observedAsHoliday,updated_at:new Date().toISOString()};if(found){const{error}=await supabase.from("learning_planner_public_holidays").update(values).eq("id",found.id).eq("institute_id",instituteId);if(error)throw error;return;}const{error}=await supabase.from("learning_planner_public_holidays").insert({institute_id:instituteId,provider:input.provider,external_id:input.externalId,created_by:profile.id,...values});if(error)throw error;}
export async function setPublicHolidayObservation(profile:AuthProfile,id:string,observed:boolean):Promise<void>{const supabase=await createClient();const{data,error}=await supabase.from("learning_planner_public_holidays").update({observed_as_holiday:observed,updated_at:new Date().toISOString()}).eq("id",id).eq("institute_id",institute(profile)).select("id").maybeSingle();if(error)throw error;if(!data)throw new Error("PLANNER_HOLIDAY_NOT_FOUND");}
