import type { HolidayScope } from "@/features/learning-planner/types/learning-planner";

export const INDIA_HOLIDAY_PROVIDER = "INDIA_POST";
export interface ProviderHoliday { externalId:string;provider:string;name:string;date:string;scope:Extract<HolidayScope,"national"|"state">;subdivisionCode:string|null }
interface IndiaPostHoliday { name:string;date:string;day:string }
const STATE_CIRCLES:Record<string,string>={"IN-AN":"Andaman & Nicobar Islands (West Bengal Circle)","IN-AP":"Andhra Pradesh Circle","IN-AR":"Arunachal Pradesh ( North East Circle )","IN-AS":"Assam Circle","IN-BR":"Bihar Circle","IN-CH":"Punjab Circle","IN-CT":"Chhattisgarh Circle","IN-DL":"Delhi Circle","IN-GA":"Goa Circle","IN-GJ":"Gujarat Circle","IN-HR":"Haryana Circle","IN-HP":"Himachal Pradesh Circle","IN-JH":"Jharkhand Circle","IN-KA":"Karnataka Circle","IN-KL":"Kerala Circle","IN-LA":"Jammu & Kashmir Circle","IN-MP":"Madhya Pradesh Circle","IN-MH":"Maharashtra Circle","IN-MN":"Manipur (North East Circle)","IN-ML":"Meghalaya (North East Circle)","IN-MZ":"Mizoram (North East Circle)","IN-NL":"Nagaland (North East Circle)","IN-OD":"Odisha Circle","IN-PY":"Tamil Nadu Circle","IN-PB":"Punjab Circle","IN-RJ":"Rajasthan Circle","IN-TN":"Tamil Nadu Circle","IN-TG":"Telangana Circle","IN-TR":"Tripura (North East Circle)","IN-UP":"Uttar Pradesh Circle","IN-UT":"Uttarakhand Circle","IN-WB":"West Bengal Circle"};
const MONTHS:Record<string,string>={January:"01",February:"02",March:"03",April:"04",May:"05",June:"06",July:"07",August:"08",September:"09",October:"10",November:"11",December:"12"};
function extractArray(source:string,key:string):unknown[]{const marker=`"${key}":[`;const start=source.indexOf(marker);if(start<0)return[];const from=start+marker.length-1;let depth=0;let quoted=false;let escaped=false;for(let index=from;index<source.length;index++){const char=source[index];if(escaped){escaped=false;continue;}if(char==="\\"){escaped=true;continue;}if(char==='"')quoted=!quoted;if(quoted)continue;if(char==='[')depth++;if(char===']'&&--depth===0){try{return JSON.parse(source.slice(from,index+1)) as unknown[];}catch{return[];}}}return[];}
function dateValue(value:string):string|null{const match=/^(\d{2})-([A-Za-z]+)-(\d{4})$/.exec(value);if(!match||!MONTHS[match[2]])return null;return `${match[3]}-${MONTHS[match[2]]}-${match[1]}`;}
export function normalizeIndiaPostHolidays(html:string,stateCode:string|null):ProviderHoliday[]{const source=html.replaceAll('\\"','"').replaceAll("\\'", "'");const groups:[unknown[],"national"|"state",string|null][]=[[extractArray(source,"All India"),"national",null]];const circle=stateCode?STATE_CIRCLES[stateCode]:null;if(circle)groups.push([extractArray(source,circle),"state",stateCode]);const unique=new Map<string,ProviderHoliday>();groups.forEach(([rows,scope,subdivisionCode])=>rows.forEach(value=>{const row=value as Partial<IndiaPostHoliday>;if(typeof row.name!=="string"||typeof row.date!=="string")return;const date=dateValue(row.date);const name=row.name.trim().replace(/\s+/g," ").toUpperCase();if(!date||!name)return;const key=`${date}:${name}`;if(unique.has(key))return;unique.set(key,{externalId:`${date}:${scope}:${subdivisionCode??"IN"}:${name}`,provider:INDIA_HOLIDAY_PROVIDER,name,date,scope,subdivisionCode});}));return[...unique.values()].sort((left,right)=>left.date.localeCompare(right.date)||left.name.localeCompare(right.name));}
export async function requestIndiaHolidays(year:number,stateCode:string|null,fetcher:typeof fetch):Promise<ProviderHoliday[]>{if(!Number.isInteger(year)||year<2000||year>2100)return[];const options={signal:AbortSignal.timeout(8_000),next:{revalidate:86_400},headers:{Accept:"text/html"}};const response=await fetcher(`https://www.indiapost.gov.in/holidays-list?year=${year}`,options);if(!response.ok)throw new Error(`HOLIDAY_PROVIDER_${response.status}`);const page=await response.text();const path=/src="([^"]*holidays-list\/page-[^"]+\.js)"/.exec(page)?.[1];if(!path)throw new Error("HOLIDAY_PROVIDER_INVALID_RESPONSE");const bundleResponse=await fetcher(new URL(path,"https://www.indiapost.gov.in").toString(),options);if(!bundleResponse.ok)throw new Error(`HOLIDAY_PROVIDER_${bundleResponse.status}`);const holidays=normalizeIndiaPostHolidays(await bundleResponse.text(),stateCode);if(!holidays.length)throw new Error("HOLIDAY_PROVIDER_INVALID_RESPONSE");return holidays;}
