import "server-only";
import type { AuthProfile } from "@/features/auth/types/auth";
import type { Batch, BatchActionResult, BatchFormOptions } from "@/features/batches/types/batch";
import type { BatchFormValues, BatchTimetableValues } from "@/features/batches/validations/batch-schema";
import { createClient } from "@/lib/supabase/server";

type Relation<T> = T|T[]|null;
type DbClient=Awaited<ReturnType<typeof createClient>>;
interface BatchRow {id:string;name:string;academic_year_id:string|null;branch_id:string|null;board_id:string|null;class_id:string|null;subject_id:string|null;is_active:boolean|null;created_at:string|null;academic_year:Relation<{name:string}>;branch:Relation<{name:string}>;board:Relation<{name:string}>;academic_class:Relation<{class_name:string}>;subject:Relation<{subject_name:string}>;schedules:Array<{id:string;day_of_week:number;start_time:string;end_time:string;effective_from:string;effective_to:string|null;is_active:boolean}>|null}
const one=<T>(value:Relation<T>):T|null=>!value?null:Array.isArray(value)?value[0]??null:value;
const institute=(profile:AuthProfile)=>{if(!profile.instituteId)throw new Error("BATCH_UNAUTHORIZED");return profile.instituteId;};
const SELECT="id,name,academic_year_id,branch_id,board_id,class_id,subject_id,is_active,created_at,academic_year:academic_years!batches_academic_year_fkey(name),branch:branches!batches_branch_fkey(name),board:boards!batches_board_id_fkey(name),academic_class:academic_classes!batches_class_id_fkey(class_name),subject:subjects!batches_subject_id_fkey(subject_name),schedules:class_schedules!class_schedules_batch_fkey(id,day_of_week,start_time,end_time,effective_from,effective_to,is_active)";
function map(row:BatchRow):Batch{const boardName=one(row.board)?.name??null;const className=one(row.academic_class)?.class_name??null;return{id:row.id,name:row.name,academicYearId:row.academic_year_id,academicYearName:one(row.academic_year)?.name??null,branchId:row.branch_id,branchName:one(row.branch)?.name??null,boardId:row.board_id,boardName,boardIds:row.board_id?[row.board_id]:[],boardNames:boardName?[boardName]:[],classId:row.class_id,className,classIds:row.class_id?[row.class_id]:[],classNames:className?[className]:[],subjectId:row.subject_id,subjectName:one(row.subject)?.subject_name??null,isActive:row.is_active===true,createdAt:row.created_at,schedules:(row.schedules??[]).map(s=>({id:s.id,dayOfWeek:s.day_of_week,startTime:s.start_time.slice(0,5),endTime:s.end_time.slice(0,5),effectiveFrom:s.effective_from,effectiveTo:s.effective_to,isActive:s.is_active})).sort((a,b)=>a.dayOfWeek-b.dayOfWeek||a.startTime.localeCompare(b.startTime))};}
async function attachBoards(db:DbClient,batches:Batch[]):Promise<Batch[]>{if(!batches.length)return batches;const ids=batches.map(batch=>batch.id);const{data:links,error}=await db.from("batch_boards").select("batch_id,board_id").in("batch_id",ids);if(error)throw error;const boardIds=[...new Set((links??[]).map(link=>link.board_id))];if(!boardIds.length)return batches;const{data:boards,error:boardError}=await db.from("boards").select("id,name").in("id",boardIds);if(boardError)throw boardError;const names=new Map((boards??[]).map(board=>[board.id,board.name]));const grouped=new Map<string,string[]>();for(const link of links??[]){const current=grouped.get(link.batch_id)??[];current.push(link.board_id);grouped.set(link.batch_id,current);}return batches.map(batch=>{const selected=[...new Set(grouped.get(batch.id)??batch.boardIds)].sort((a,b)=>(names.get(a)??a).localeCompare(names.get(b)??b));return{...batch,boardIds:selected,boardNames:selected.map(id=>names.get(id)).filter((name):name is string=>Boolean(name))};});}
async function attachClasses(db:DbClient,batches:Batch[]):Promise<Batch[]>{if(!batches.length)return batches;const ids=batches.map(batch=>batch.id);const{data:links,error}=await db.from("batch_classes").select("batch_id,class_id").in("batch_id",ids);if(error)throw error;const classIds=[...new Set((links??[]).map(link=>link.class_id))];if(!classIds.length)return batches;const{data:classes,error:classError}=await db.from("academic_classes").select("id,class_name").in("id",classIds);if(classError)throw classError;const names=new Map((classes??[]).map(item=>[item.id,item.class_name]));const grouped=new Map<string,string[]>();for(const link of links??[]){const current=grouped.get(link.batch_id)??[];current.push(link.class_id);grouped.set(link.batch_id,current);}return batches.map(batch=>{const selected=[...new Set(grouped.get(batch.id)??batch.classIds)].sort((a,b)=>(names.get(a)??a).localeCompare(names.get(b)??b));return{...batch,classIds:selected,classNames:selected.map(id=>names.get(id)).filter((name):name is string=>Boolean(name))};});}
async function attachMappings(db:DbClient,batches:Batch[]):Promise<Batch[]>{return attachClasses(db,await attachBoards(db,batches));}
export async function listBatches(profile:AuthProfile):Promise<Batch[]>{const db=await createClient();const{data,error}=await db.from("batches").select(SELECT).eq("institute_id",institute(profile)).order("name");if(error)throw error;return attachMappings(db,(data as unknown as BatchRow[]).map(map));}
export async function getBatch(profile:AuthProfile,id:string):Promise<Batch|null>{const db=await createClient();const{data,error}=await db.from("batches").select(SELECT).eq("institute_id",institute(profile)).eq("id",id).maybeSingle();if(error)throw error;if(!data)return null;const [batch]=await attachMappings(db,[map(data as unknown as BatchRow)]);return batch??null;}
export async function listBatchFormOptions(profile:AuthProfile):Promise<BatchFormOptions>{const db=await createClient(),scope=institute(profile);const[years,branches,boards,classes,subjects]=await Promise.all([db.from("academic_years").select("id,name").eq("institute_id",scope).eq("is_active",true).order("start_date"),db.from("branches").select("id,name").eq("institute_id",scope).eq("is_active",true).order("name"),db.from("boards").select("id,name").eq("institute_id",scope).order("name"),db.from("academic_classes").select("id,class_name").eq("institute_id",scope).order("class_name"),db.from("subjects").select("id,subject_name").eq("institute_id",scope).order("subject_name")]);const error=years.error??branches.error??boards.error??classes.error??subjects.error;if(error)throw error;return{academicYears:(years.data??[]).map(v=>({id:v.id,label:v.name})),branches:(branches.data??[]).map(v=>({id:v.id,label:v.name})),boards:(boards.data??[]).map(v=>({id:v.id,label:v.name})),classes:(classes.data??[]).map(v=>({id:v.id,label:v.class_name})),subjects:(subjects.data??[]).map(v=>({id:v.id,label:v.subject_name}))};}
export async function createTeachingBatch(values:BatchFormValues,approveOverlap:boolean):Promise<BatchActionResult>{const db=await createClient();const{data,error}=await db.rpc("create_teaching_batch",{p_input:values,p_approve_overlap:approveOverlap});if(error)throw error;const result=data as {status:"success"|"conflict";batchId?:string;conflicts?:BatchActionResult extends {status:"conflict";conflicts:infer C}?C:never};if(result.status==="conflict")return{status:"conflict",message:"This schedule overlaps another active Batch.",conflicts:result.conflicts??[]};return{status:"success",message:"Batch and recurring timetable created.",batchId:result.batchId};}
export async function replaceBatchTimetable(values:BatchTimetableValues,approveOverlap:boolean):Promise<BatchActionResult>{const db=await createClient();const{data,error}=await db.rpc("replace_batch_timetable",{p_batch_id:values.batchId,p_effective_from:values.effectiveFrom,p_schedules:values.schedules,p_approve_overlap:approveOverlap,p_reason:values.overlapReason??null});if(error)throw error;const result=data as {status:"success"|"conflict";conflicts?:never[]};if(result.status==="conflict")return{status:"conflict",message:"This schedule overlaps another active Batch.",conflicts:(result.conflicts??[]) as never[]};return{status:"success",message:"Future Batch timetable updated."};}
export async function deleteBatchRecord(_profile:AuthProfile,id:string):Promise<boolean>{const db=await createClient();const{data,error}=await db.rpc("delete_teaching_batch",{p_batch_id:id});if(error)throw error;return data===true;}
export async function setBatchStatus(profile:AuthProfile,id:string,isActive:boolean):Promise<boolean>{const db=await createClient();const { data, error } = await db.from("batches").update({ is_active: isActive }).eq("institute_id", institute(profile)).eq("id", id).select("id").maybeSingle(); if (error) throw error; return Boolean(data);}
