"use client";

import { CheckCircle2, LockKeyhole, Mail, ShieldCheck } from "lucide-react";
import { useRouter } from "next/navigation";
import { useMemo, useState, useTransition } from "react";

import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { toast, Toaster } from "@/components/ui/toast";
import { requestEnrollmentOtpAction, submitEnrollmentAction, verifyEnrollmentOtpAction } from "@/features/student-enrollment/actions/enrollment-actions";
import type { EnrollmentInviteView, EnrollmentPurpose } from "@/features/student-enrollment/services/enrollment-service";

const fieldClass="flex h-9 w-full rounded-md border border-input bg-transparent px-3 py-1 text-sm shadow-xs outline-none focus-visible:border-ring focus-visible:ring-[3px] focus-visible:ring-ring/50";
const upper=(value:string)=>value.toLocaleUpperCase("en-IN");

function EmailVerification({token,purpose,label,email,onEmail,verifiedEmail,onVerified,noEmail,onNoEmail}:{token:string;purpose:EnrollmentPurpose;label:string;email:string;onEmail:(value:string)=>void;verifiedEmail:string|null;onVerified:(value:string)=>void;noEmail:boolean;onNoEmail:(value:boolean)=>void}){
  const[otp,setOtp]=useState("");const[isPending,startTransition]=useTransition();const verified=!noEmail&&verifiedEmail===email.trim().toLowerCase()&&Boolean(email);
  function toggleNoEmail(checked:boolean){onNoEmail(checked);if(checked){onEmail("");onVerified("");setOtp("");}}
  return <div className="space-y-3 rounded-xl border p-4"><div className="flex flex-wrap items-center justify-between gap-3"><label className="text-sm font-medium">{label}</label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={noEmail} onChange={(e)=>toggleNoEmail(e.target.checked)}/>No email</label></div>
    <div className="grid gap-2 sm:grid-cols-[minmax(0,1fr)_auto]"><Input className="h-11 min-w-0 text-base" type="email" disabled={noEmail} value={email} onChange={(e)=>{onEmail(e.target.value.toLowerCase());if(verifiedEmail&&e.target.value.toLowerCase()!==verifiedEmail)onVerified("");}} placeholder={noEmail?"No email selected":"name@example.com"}/><Button className="h-11" type="button" variant="outline" disabled={noEmail||isPending||!email||verified} onClick={()=>startTransition(async()=>{const r=await requestEnrollmentOtpAction(token,purpose,email);toast.add({title:r.status==="success"?"OTP sent":"Unable to send OTP",description:r.message,type:r.status==="success"?"success":"error"});})}><Mail/>Send OTP</Button></div>
    {noEmail?<p className="text-xs text-muted-foreground">No portal login will be created for this person unless an email is added later by the institute.</p>:verified?<p className="flex items-center gap-1 text-sm text-emerald-700"><CheckCircle2 className="size-4"/>Verified</p>:<div className="grid gap-2 sm:grid-cols-[minmax(0,1fr)_auto]"><Input className="h-11" inputMode="numeric" maxLength={6} value={otp} onChange={(e)=>setOtp(e.target.value.replace(/\D/g,"").slice(0,6))} placeholder="6-digit OTP"/><Button className="h-11" type="button" disabled={isPending||otp.length!==6||!email} onClick={()=>startTransition(async()=>{const r=await verifyEnrollmentOtpAction(token,purpose,email,otp);if(r.status==="success"){onVerified(r.email);setOtp("");}toast.add({title:r.status==="success"?"Email verified":"Verification failed",description:r.message,type:r.status==="success"?"success":"error"});})}><ShieldCheck/>Verify</Button></div>}
  </div>;
}

export function ParentEnrollmentForm({invite}:{invite:EnrollmentInviteView}){
  const router=useRouter();const[isPending,startTransition]=useTransition();
  const[name,setName]=useState("");const[motherName,setMotherName]=useState("");const[gender,setGender]=useState("Male");const[dateOfBirth,setDateOfBirth]=useState("");const[studentMobile,setStudentMobile]=useState("");const[studentEmail,setStudentEmail]=useState("");const[studentNoEmail,setStudentNoEmail]=useState(false);const[verifiedStudentEmail,setVerifiedStudentEmail]=useState(invite.studentEmailVerified??"");const[schoolName,setSchoolName]=useState("");const[address,setAddress]=useState("");const[parentName,setParentName]=useState("");const[relationship,setRelationship]=useState("Father");const[parentEmail,setParentEmail]=useState("");const[parentNoEmail,setParentNoEmail]=useState(false);const[verifiedParentEmail,setVerifiedParentEmail]=useState(invite.parentEmailVerified??"");const[parentRequest,setParentRequest]=useState("");const[rulesAccepted,setRulesAccepted]=useState(false);
  const today=new Date().toISOString().slice(0,10);const studentVerified=!studentNoEmail&&verifiedStudentEmail===studentEmail.trim().toLowerCase()&&Boolean(studentEmail);const parentVerified=!parentNoEmail&&verifiedParentEmail===parentEmail.trim().toLowerCase()&&Boolean(parentEmail);const emailChoiceValid=!(studentNoEmail&&parentNoEmail);const emailVerificationValid=(studentNoEmail||studentVerified)&&(parentNoEmail||parentVerified);const emailsDifferent=!studentEmail||!parentEmail||studentEmail.trim().toLowerCase()!==parentEmail.trim().toLowerCase();const canSubmit=useMemo(()=>emailChoiceValid&&emailVerificationValid&&emailsDifferent&&rulesAccepted&&Boolean(name.trim())&&Boolean(dateOfBirth)&&studentMobile.length===10&&Boolean(parentName.trim()),[emailChoiceValid,emailVerificationValid,emailsDifferent,rulesAccepted,name,dateOfBirth,studentMobile,parentName]);const currency=new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR"});
  function submit(){startTransition(async()=>{const result=await submitEnrollmentAction(invite.token,{name,motherName,gender,dateOfBirth,studentMobile,studentEmail:studentNoEmail?"":studentEmail,studentNoEmail,schoolName,address,parentName,relationship,parentEmail:parentNoEmail?"":parentEmail,parentNoEmail,parentRequest,rulesAccepted});if(result.status==="error"){toast.add({title:"Unable to submit enrollment",description:result.message,type:"error"});return;}router.push(`/enroll/${invite.token}/success`);});}

  return <div className="mx-auto max-w-4xl space-y-6 px-4 py-8"><Toaster/><div className="text-center"><p className="text-sm font-semibold uppercase tracking-[0.2em] text-muted-foreground">English Remedial Classes</p><h1 className="mt-2 text-3xl font-bold">Learning Is Fun</h1><p className="mt-2 text-muted-foreground">Student Enrollment Form</p></div>
    <Card><CardHeader><CardTitle>Enrollment Details</CardTitle></CardHeader><CardContent className="grid gap-4 sm:grid-cols-3"><div><p className="text-xs text-muted-foreground">Academic Year</p><p className="font-medium">{invite.academicYearName}</p></div><div><p className="text-xs text-muted-foreground">Class</p><p className="font-medium">{invite.className}</p></div><div><p className="text-xs text-muted-foreground">Parent WhatsApp</p><p className="flex items-center gap-1 font-medium"><LockKeyhole className="size-4"/>{invite.parentMobile}</p><p className="text-xs text-muted-foreground">Locked by institute</p></div></CardContent></Card>
    <Card><CardHeader><CardTitle>Student Details</CardTitle></CardHeader><CardContent className="grid gap-4 sm:grid-cols-2"><label className="space-y-2 text-sm font-medium">Student Name *<Input value={name} onChange={(e)=>setName(upper(e.target.value))} className="uppercase"/></label><label className="space-y-2 text-sm font-medium">Mother Name<Input value={motherName} onChange={(e)=>setMotherName(upper(e.target.value))} className="uppercase"/></label><label className="space-y-2 text-sm font-medium">Date of Birth *<Input type="date" max={today} value={dateOfBirth} onChange={(e)=>setDateOfBirth(e.target.value)}/></label><label className="space-y-2 text-sm font-medium">Gender *<select className={fieldClass} value={gender} onChange={(e)=>setGender(e.target.value)}><option>Male</option><option>Female</option><option>Other</option></select></label><label className="space-y-2 text-sm font-medium">Student Mobile *<Input inputMode="numeric" maxLength={10} value={studentMobile} onChange={(e)=>setStudentMobile(e.target.value.replace(/\D/g,"").slice(0,10))} placeholder="10-digit mobile"/></label><label className="space-y-2 text-sm font-medium">School Name<Input value={schoolName} onChange={(e)=>setSchoolName(upper(e.target.value))} className="uppercase" placeholder="School name"/></label><div className="sm:col-span-2"><EmailVerification token={invite.token} purpose="STUDENT" label="Student Email" email={studentEmail} onEmail={setStudentEmail} verifiedEmail={verifiedStudentEmail||null} onVerified={setVerifiedStudentEmail} noEmail={studentNoEmail} onNoEmail={setStudentNoEmail}/></div><label className="space-y-2 text-sm font-medium sm:col-span-2">Address<textarea className={`${fieldClass} min-h-24 resize-y py-2 uppercase`} value={address} onChange={(e)=>setAddress(upper(e.target.value))}/></label></CardContent></Card>
    <Card><CardHeader><CardTitle>Parent / Guardian Details</CardTitle></CardHeader><CardContent className="grid gap-4 sm:grid-cols-2"><label className="space-y-2 text-sm font-medium">Father / Guardian Name *<Input value={parentName} onChange={(e)=>setParentName(upper(e.target.value))} className="uppercase"/></label><label className="space-y-2 text-sm font-medium">Relationship *<select className={fieldClass} value={relationship} onChange={(e)=>setRelationship(e.target.value)}><option>Father</option><option>Mother</option><option>Guardian</option></select></label><label className="space-y-2 text-sm font-medium">WhatsApp / Phone Number *<Input value={invite.parentMobile} disabled/><span className="text-xs text-muted-foreground">This number came from the secure WhatsApp enrollment link and cannot be changed.</span></label><div className="sm:col-span-2"><EmailVerification token={invite.token} purpose="PARENT" label="Parent Email" email={parentEmail} onEmail={setParentEmail} verifiedEmail={verifiedParentEmail||null} onVerified={setVerifiedParentEmail} noEmail={parentNoEmail} onNoEmail={setParentNoEmail}/></div></CardContent></Card>
    <Card><CardHeader><CardTitle>Comments / Request</CardTitle></CardHeader><CardContent><label className="space-y-2 text-sm font-medium">Comments or Request <span className="font-normal text-muted-foreground">(Optional)</span><textarea maxLength={1000} className={`${fieldClass} min-h-28 resize-y py-2 uppercase`} value={parentRequest} onChange={(e)=>setParentRequest(upper(e.target.value))} placeholder="Any comment or request for Learning Is Fun"/></label></CardContent></Card>
    <Card><CardHeader><CardTitle>Portal Access</CardTitle></CardHeader><CardContent className="space-y-2 text-sm"><p>At least one email address is required and every email entered must be OTP verified.</p><p><strong>Student Email provided:</strong> Student Portal login will be created.</p><p><strong>Parent Email provided:</strong> Parent Portal login will be created.</p><p><strong>Both provided:</strong> Both portals will be available.</p>{!emailChoiceValid?<p className="font-medium text-destructive">Student and Parent cannot both be marked No email.</p>:null}{!emailsDifferent?<p className="font-medium text-destructive">Student and Parent Email must be different.</p>:null}</CardContent></Card>
    <Card><CardHeader><CardTitle>Fees</CardTitle></CardHeader><CardContent className="space-y-3"><p className="text-sm text-muted-foreground">Amounts are fixed by Learning Is Fun. Parents cannot edit fees, security deposit, or discounts.</p>{invite.feeItems.map((item)=>{const amount=item.feeNature==="refundable_deposit"?invite.securityDepositAmount:item.amount;return <div key={item.id} className="flex items-center justify-between rounded-xl border p-3"><div><p className="font-medium">{item.name}</p><p className="text-xs uppercase text-muted-foreground">{item.feeNature.replaceAll("_"," ")} · {item.scheduleType.replaceAll("_"," ")}</p></div><p className="font-semibold">{currency.format(amount)}</p></div>})}</CardContent></Card>
    <Card><CardContent className="space-y-4 p-6"><label className="flex items-start gap-3 text-sm"><input type="checkbox" className="mt-1 size-4" checked={rulesAccepted} onChange={(e)=>setRulesAccepted(e.target.checked)}/><span>I have read and agree with the <strong>Rules &amp; Regulations of Learning Is Fun</strong>. *</span></label><div className="rounded-xl bg-muted/40 p-3 text-xs text-muted-foreground">By submitting this form, the parent/guardian confirms that the information provided is correct and accepts the institute&apos;s applicable rules and regulations.</div><Button size="lg" className="w-full" disabled={!canSubmit||isPending} onClick={submit}>{isPending?"Submitting…":"Submit Enrollment Form"}</Button>{!emailVerificationValid?<p className="text-center text-sm text-amber-700">Every email provided must be OTP verified before submission.</p>:null}</CardContent></Card>
  </div>;
}
