import { z } from "zod";
const optionalUuid=z.union([z.string().uuid(),z.literal("")]).optional().transform(v=>v||undefined);
export const practiceSetSchema=z.object({id:optionalUuid,academicYearId:z.string().uuid(),title:z.string().trim().min(1).max(150).transform(v=>v.toUpperCase()),description:z.string().trim().max(1000).optional().transform(v=>v? v.toUpperCase():undefined),answerMode:z.enum(["after_each_question","after_completion"]),allowRetry:z.boolean(),maxAttempts:z.coerce.number().int().min(1).max(20).optional(),marksMode:z.enum(["same_for_all","custom","ai_suggested"]),defaultMarks:z.coerce.number().positive().max(100).optional(),targetTotalMarks:z.coerce.number().positive().max(10000).optional(),questionIds:z.array(z.string().uuid()).min(1),questionMarks:z.record(z.string().uuid(),z.coerce.number().positive().max(100)).optional()}).superRefine((v,c)=>{if(v.marksMode==="same_for_all"&&!v.defaultMarks)c.addIssue({code:"custom",path:["defaultMarks"],message:"Default marks are required."});if(v.marksMode==="custom"&&v.questionIds.some(id=>!v.questionMarks?.[id]))c.addIssue({code:"custom",path:["questionMarks"],message:"Enter marks for every selected Question."})});
export const practiceSetIdSchema=z.object({id:z.string().uuid()});
const optionalLocalDateTime=z.union([z.string().datetime({local:true}),z.literal("")]).optional().transform(v=>v||undefined);
export const assignmentSchema=z.object({practiceSetId:z.string().uuid(),batchId:optionalUuid,studentIds:z.array(z.string().uuid()).optional(),scheduleEventId:optionalUuid,availableFrom:optionalLocalDateTime,dueAt:optionalLocalDateTime}).superRefine((v,c)=>{if(!v.batchId&&!v.studentIds?.length)c.addIssue({code:"custom",path:["studentIds"],message:"Select a Batch or Students."});if(v.availableFrom&&v.dueAt&&v.dueAt<v.availableFrom)c.addIssue({code:"custom",path:["dueAt"],message:"Due date must follow availability."})});
export const attemptStartSchema=z.object({assignmentId:z.string().uuid()});
export const attemptSubmitSchema=z.object({attemptId:z.string().uuid(),answers:z.array(z.object({questionId:z.string().uuid(),answer:z.union([z.string(),z.boolean(),z.array(z.string())])}))});
export const retrySchema=z.object({attemptId:z.string().uuid()});
