"use client";
import { useMemo, useState } from "react";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import type { BankQuestion, PracticeOptions, QuestionTemplate } from "@/features/practice-work/types/practice-work";

export function QuestionBankManager({questions,options,selectedIds,onSelectionChange}:{questions:BankQuestion[];templates:QuestionTemplate[];options:PracticeOptions;selectedIds?:string[];onSelectionChange?:(ids:string[])=>void}) {
  const [search,setSearch]=useState(""),[board,setBoard]=useState(""),[academicClass,setClass]=useState(""),[subject,setSubject]=useState(""),[source,setSource]=useState(""),[type,setType]=useState(""),[book,setBook]=useState(""),[chapter,setChapter]=useState(""),[fullMarks,setFullMarks]=useState(""),[questionDate,setQuestionDate]=useState("");
  const filtered=useMemo(()=>questions.filter((q)=>{const text=`${q.questionText} ${q.bookName??""} ${q.chapter??""}`.toLowerCase();return(!search||text.includes(search.toLowerCase()))&&(!board||q.boardId===board)&&(!academicClass||q.classId===academicClass)&&(!subject||q.subjectId===subject)&&(!source||q.sourceType===source)&&(!type||q.questionType===type)&&(!book||(q.bookName??"").toLowerCase().includes(book.toLowerCase()))&&(!chapter||(q.chapter??"").toLowerCase().includes(chapter.toLowerCase()))&&(!fullMarks||q.sourceFullMarks===Number(fullMarks))&&(!questionDate||q.questionExamDate===questionDate)}),[questions,search,board,academicClass,subject,source,type,book,chapter,fullMarks,questionDate]);
  const toggle=(id:string,checked:boolean)=>onSelectionChange?.(checked?[...(selectedIds??[]),id]:(selectedIds??[]).filter((value)=>value!==id));
  return <div className="space-y-5"><p className="text-sm text-muted-foreground">Permanent approved Question library.{onSelectionChange?` ${selectedIds?.length??0} selected for Practice Work.`:""}</p><Card><CardContent className="grid gap-3 p-5 sm:grid-cols-2 lg:grid-cols-4"><label className="text-sm">Search<Input value={search} onChange={(e)=>setSearch(e.target.value)}/></label><Filter label="Board" value={board} set={setBoard} options={options.boards}/><Filter label="Class" value={academicClass} set={setClass} options={options.classes}/><Filter label="Subject" value={subject} set={setSubject} options={options.subjects??[]}/><Filter label="Source" value={source} set={setSource} options={[{id:"ai",label:"AI"},{id:"import",label:"Import"},{id:"manual",label:"Manual"}]}/><Filter label="Question Type" value={type} set={setType} options={[...new Set(questions.map((q)=>q.questionType))].map((value)=>({id:value,label:value.replaceAll("_"," ")}))}/><label className="text-sm">Book<Input value={book} onChange={(e)=>setBook(e.target.value)}/></label><label className="text-sm">Chapter<Input value={chapter} onChange={(e)=>setChapter(e.target.value)}/></label><label className="text-sm">Source Full Marks<Input type="number" value={fullMarks} onChange={(e)=>setFullMarks(e.target.value)}/></label><label className="text-sm">Question / Exam Date<Input type="date" value={questionDate} onChange={(e)=>setQuestionDate(e.target.value)}/></label></CardContent></Card><div className="grid gap-4 lg:grid-cols-2">{filtered.length?filtered.map((q)=><Card key={q.id}><CardContent className="space-y-2 p-5"><div className="flex justify-between gap-3"><div className="flex items-start gap-3">{onSelectionChange?<input type="checkbox" aria-label={`Select ${q.questionText}`} checked={selectedIds?.includes(q.id)??false} onChange={(e)=>toggle(q.id,e.target.checked)}/>:null}<p className="font-semibold">{q.questionText}</p></div><Badge>{q.sourceType}</Badge></div><p className="text-sm text-muted-foreground">{q.questionType.replaceAll("_"," ")} · {q.difficulty} · {q.suggestedMarks??"—"} marks</p><p className="text-xs">{[q.boardName,q.className,q.subjectName,q.bookName,q.chapter].filter(Boolean).join(" · ")||"General"}</p><p className="text-xs text-muted-foreground">Source Full Marks: {q.sourceFullMarks??"Not set"} · Question Date: {q.questionExamDate??"Not set"}</p></CardContent></Card>):<Card><CardContent className="p-8 text-center text-muted-foreground">No approved Questions match these filters.</CardContent></Card>}</div></div>;
}
function Filter({label,value,set,options}:{label:string;value:string;set:(value:string)=>void;options:{id:string;label:string}[]}){return <label className="text-sm">{label}<select value={value} onChange={(e)=>set(e.target.value)} className="mt-1 h-10 w-full rounded-xl border bg-card px-3"><option value="">All</option>{options.map((option)=><option key={option.id} value={option.id}>{option.label}</option>)}</select></label>}
