"use client";

import { BarChart3, CalendarCheck, CheckCircle2, Clock3, GraduationCap, ListChecks, Umbrella, UserX, Users } from "lucide-react";
import Link from "next/link";
import { useState } from "react";

import { EmptyState } from "@/components/dashboard/empty-state";
import { StatCard } from "@/components/dashboard/stat-card";
import { PageHeader } from "@/components/layout/page-header";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { AttendanceCalendar } from "@/features/attendance-reports/components/attendance-calendar";
import { AttendanceStatusBadge } from "@/features/attendance-reports/components/attendance-status-badge";
import type { AttendanceReportOptions, AttendanceReportResult, AttendanceTotals } from "@/features/attendance-reports/types/attendance-report";
import type { AttendanceReportFilters } from "@/features/attendance-reports/validations/attendance-report-schema";
import { ATTENDANCE_STATUSES } from "@/features/attendance/types/attendance";

const selectClassName = "h-10 w-full rounded-xl border border-input bg-card px-3 text-sm outline-none focus-visible:border-ring focus-visible:ring-3 focus-visible:ring-ring/30";
const titles = { student: "Student Attendance Summary", batch: "Batch Attendance Summary", daily: "Daily Attendance Summary", "academic-year": "Academic Year Summary", status: "Attendance Status Report" } as const;
function percentage(value: number | null): string { return value === null ? "—" : `${value.toFixed(1)}%`; }
function SummaryCards({ totals, students }: { totals: AttendanceTotals; students?: number }) { return <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4 2xl:grid-cols-7">{students !== undefined ? <StatCard title="Students" value={students.toString()} description="Represented Students" icon={Users} tone="blue" /> : null}<StatCard title="Present" value={totals.presentCount.toString()} description="Stored Present records" icon={CheckCircle2} tone="emerald" /><StatCard title="Late" value={totals.lateCount.toString()} description="Stored Late records" icon={Clock3} tone="amber" /><StatCard title="Effective Present" value={totals.effectivePresentCount.toString()} description="Present + Late" icon={CheckCircle2} tone="emerald" /><StatCard title="Absent" value={totals.absentCount.toString()} description="Absent records" icon={UserX} tone="rose" /><StatCard title="Leave" value={totals.leaveCount.toString()} description="Leave records" icon={Umbrella} tone="violet" /><StatCard title="Total" value={totals.totalCount.toString()} description="Attendance records" icon={ListChecks} tone="blue" /><StatCard title="Attendance" value={percentage(totals.attendancePercentage)} description="Effective Present / Total" icon={BarChart3} tone="emerald" /></div>; }

export function AttendanceReportsManager({ options, filters, result, error }: { options: AttendanceReportOptions; filters: AttendanceReportFilters; result: AttendanceReportResult | null; error: string | null }) {
  const [report, setReport] = useState(filters.report);
  const historyParams = new URLSearchParams(); if (filters.dateFrom) historyParams.set("dateFrom", filters.dateFrom); if (filters.dateTo) historyParams.set("dateTo", filters.dateTo); if (filters.status) historyParams.set("status", filters.status);
  return <div className="space-y-6"><PageHeader title="Attendance Reports" description="Analyse Attendance using stored historical Academic Year, Batch and Assignment context." icon={BarChart3} theme="attendance" eyebrow="Academics" />
    <Card><CardContent className="p-4 sm:p-6"><form method="get" className="grid gap-3 md:grid-cols-2 xl:grid-cols-4"><div className="space-y-1 md:col-span-2 xl:col-span-4"><label htmlFor="report-type" className="text-xs font-medium">Report</label><select id="report-type" name="report" className={selectClassName} value={report} onChange={(event) => setReport(event.target.value as AttendanceReportFilters["report"])}>{Object.entries(titles).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></div>{report === "daily" ? <div className="space-y-1"><label htmlFor="report-date" className="text-xs font-medium">Attendance Date</label><Input id="report-date" type="date" name="attendanceDate" defaultValue={filters.attendanceDate} /></div> : <><div className="space-y-1"><label htmlFor="report-from" className="text-xs font-medium">Date From</label><Input id="report-from" type="date" name="dateFrom" defaultValue={filters.dateFrom} /></div><div className="space-y-1"><label htmlFor="report-to" className="text-xs font-medium">Date To</label><Input id="report-to" type="date" name="dateTo" defaultValue={filters.dateTo} /></div></>}{["student", "batch", "academic-year"].includes(report) ? <div className="space-y-1"><label htmlFor="report-year" className="text-xs font-medium">Academic Year</label><select id="report-year" name="academicYearId" className={selectClassName} defaultValue={filters.academicYearId ?? ""}><option value="">Select Academic Year</option>{options.academicYears.map((x) => <option key={x.id} value={x.id}>{x.label}</option>)}</select></div> : null}{["batch", "daily"].includes(report) ? <div className="space-y-1"><label htmlFor="report-batch" className="text-xs font-medium">Batch</label><select id="report-batch" name="batchId" className={selectClassName} defaultValue={filters.batchId ?? ""}><option value="">Select Batch</option>{options.batches.map((x) => <option key={x.id} value={x.id}>{x.label}</option>)}</select></div> : null}{report === "student" ? <div className="space-y-1"><label htmlFor="report-student" className="text-xs font-medium">Student</label><select id="report-student" name="studentId" className={selectClassName} defaultValue={filters.studentId ?? ""}><option value="">Select Student</option>{options.students.map((x) => <option key={x.id} value={x.id}>{x.label}</option>)}</select></div> : null}{report === "status" ? <div className="space-y-1"><label htmlFor="report-status" className="text-xs font-medium">Status</label><select id="report-status" name="status" className={selectClassName} defaultValue={filters.status ?? ""}><option value="">Select Status</option>{ATTENDANCE_STATUSES.map((x) => <option key={x}>{x}</option>)}</select></div> : null}<div className="flex items-end gap-2 md:col-span-2 xl:col-span-4"><Button type="submit">Generate Report</Button><Button nativeButton={false} render={<Link href="/attendance/reports" />} variant="outline">Reset</Button></div></form></CardContent></Card>
    {error ? <div role="alert" className="rounded-2xl border border-destructive/30 bg-destructive/5 p-4 text-sm text-destructive">{error}</div> : null}{!result ? <EmptyState icon={BarChart3} title="Choose report filters" description="Select the required report values, then generate an institute-scoped Attendance report." /> : null}
    {result?.type === "student" ? <><SummaryCards totals={result.data} /><Card><CardContent className="space-y-5 p-4 sm:p-6"><div className="rounded-2xl bg-emerald-950 p-4 text-white"><h2 className="text-xl font-bold">Student Attendance</h2><p className="text-sm text-emerald-100">{options.students.find((x) => x.id === filters.studentId)?.label}</p></div><AttendanceCalendar entries={result.data.calendar} /></CardContent></Card></> : null}
    {result?.type === "batch" ? <><SummaryCards totals={result.data} students={result.data.students} /><Card><CardContent className="space-y-4 p-4 sm:p-6"><h2 className="rounded-2xl bg-emerald-950 p-4 text-xl font-bold text-white">Student-wise Batch Summary</h2>{result.data.rows.length ? <><div className="hidden md:block"><Table><TableHeader><TableRow><TableHead>Admission No.</TableHead><TableHead>Student</TableHead><TableHead>Present</TableHead><TableHead>Late</TableHead><TableHead>Effective Present</TableHead><TableHead>Absent</TableHead><TableHead>Leave</TableHead><TableHead>Total</TableHead><TableHead>Attendance %</TableHead></TableRow></TableHeader><TableBody>{result.data.rows.map((row) => <TableRow key={row.studentId}><TableCell>{row.admissionNumber}</TableCell><TableCell className="font-semibold">{row.studentName}</TableCell><TableCell>{row.presentCount}</TableCell><TableCell>{row.lateCount}</TableCell><TableCell>{row.effectivePresentCount}</TableCell><TableCell>{row.absentCount}</TableCell><TableCell>{row.leaveCount}</TableCell><TableCell>{row.totalCount}</TableCell><TableCell>{percentage(row.attendancePercentage)}</TableCell></TableRow>)}</TableBody></Table></div><div className="grid gap-3 md:hidden">{result.data.rows.map((row) => <article key={row.studentId} className="rounded-2xl border p-4"><p className="font-bold">{row.studentName}</p><p className="text-xs text-muted-foreground">{row.admissionNumber}</p><dl className="mt-3 grid grid-cols-3 gap-2 text-sm"><div><dt>Present</dt><dd>{row.presentCount}</dd></div><div><dt>Late</dt><dd>{row.lateCount}</dd></div><div><dt>Effective Present</dt><dd>{row.effectivePresentCount}</dd></div><div><dt>Absent</dt><dd>{row.absentCount}</dd></div><div><dt>Leave</dt><dd>{row.leaveCount}</dd></div><div><dt>Total</dt><dd>{row.totalCount}</dd></div><div><dt>Attendance</dt><dd>{percentage(row.attendancePercentage)}</dd></div></dl></article>)}</div></> : <EmptyState icon={Users} title="No Batch Attendance" description="No Attendance records match these Batch filters." compact />}</CardContent></Card></> : null}
    {result?.type === "daily" ? <><SummaryCards totals={result.data} /><Card><CardContent className="space-y-4 p-4 sm:p-6"><h2 className="rounded-2xl bg-emerald-950 p-4 text-xl font-bold text-white">Daily Student Records</h2>{result.data.rows.length ? <Table><TableHeader><TableRow><TableHead>Admission No.</TableHead><TableHead>Student</TableHead><TableHead>Status</TableHead><TableHead>Remarks</TableHead></TableRow></TableHeader><TableBody>{result.data.rows.map((row) => <TableRow key={row.admissionNumber}><TableCell>{row.admissionNumber}</TableCell><TableCell className="font-semibold">{row.studentName}</TableCell><TableCell><AttendanceStatusBadge status={row.status} /></TableCell><TableCell>{row.remarks || "—"}</TableCell></TableRow>)}</TableBody></Table> : <EmptyState icon={CalendarCheck} title="No Daily Attendance" description="No saved Attendance exists for this date and Batch." compact />}</CardContent></Card></> : null}
    {result?.type === "academic-year" ? <><SummaryCards totals={result.data} /><Card><CardContent className="space-y-4 p-4 sm:p-6"><h2 className="rounded-2xl bg-emerald-950 p-4 text-xl font-bold text-white">Batch Breakdown</h2>{result.data.batches.length ? <Table><TableHeader><TableRow><TableHead>Batch</TableHead><TableHead>Present</TableHead><TableHead>Late</TableHead><TableHead>Effective Present</TableHead><TableHead>Absent</TableHead><TableHead>Leave</TableHead><TableHead>Total</TableHead><TableHead>Attendance %</TableHead></TableRow></TableHeader><TableBody>{result.data.batches.map((row) => <TableRow key={row.batchId}><TableCell className="font-semibold">{row.batchName}</TableCell><TableCell>{row.presentCount}</TableCell><TableCell>{row.lateCount}</TableCell><TableCell>{row.effectivePresentCount}</TableCell><TableCell>{row.absentCount}</TableCell><TableCell>{row.leaveCount}</TableCell><TableCell>{row.totalCount}</TableCell><TableCell>{percentage(row.attendancePercentage)}</TableCell></TableRow>)}</TableBody></Table> : <EmptyState icon={GraduationCap} title="No Academic Year Attendance" description="No records match this Academic Year." compact />}</CardContent></Card></> : null}
    {result?.type === "status" ? <Card><CardContent className="space-y-5 p-6"><div className="rounded-2xl bg-emerald-950 p-4 text-white"><h2 className="text-xl font-bold">{result.data.status} Attendance</h2><p className="text-sm text-emerald-100">Institute-scoped status totals for the selected range.</p></div><div className="grid gap-4 sm:grid-cols-3"><StatCard title="Records" value={result.data.total.toString()} description={`${result.data.status} records`} icon={ListChecks} tone="blue" /><StatCard title="Students" value={result.data.students.toString()} description="Distinct Students" icon={Users} tone="emerald" /><StatCard title="Days" value={result.data.days.toString()} description="Distinct dates" icon={CalendarCheck} tone="amber" /></div><Button nativeButton={false} render={<Link href={`/attendance/history?${historyParams}`} />}>View Matching Attendance History</Button></CardContent></Card> : null}
  </div>;
}
