import "server-only";
import mammoth from "mammoth";
import { getDocumentExtractionProvider } from "@/features/practice-work/services/document-extraction-provider";
import type { Difficulty, QuestionType } from "@/features/practice-work/types/practice-work";

export interface ExtractedDraftQuestion { questionType:QuestionType;questionText:string;options:string[]|null;correctAnswer:string;acceptedAnswers:string[]|null;explanation:string;difficulty:Difficulty;suggestedMarks:number;tags:string[];sourcePage:number|null;sourceReference:string|null;associatedImage?:Uint8Array;associatedImageMimeType?:"image/jpeg"|"image/png";extractionWarnings?:string[];visualDependency?:boolean;visualDescription?:string|null }
export interface QuestionExtractionResult { questions:ExtractedDraftQuestion[];model:string }
const numberPattern=/^(?:Q(?:UESTION)?\s*)?(\d+)[.)\-:]\s*(.+)$/i,marksPattern=/\[?\(?\s*(\d+(?:\.\d+)?)\s*(?:MARKS?|M)\s*\)?\]?\s*$/i,optionPattern=/^(?:\(?[A-Da-d]\)|[A-Da-d][.)])\s*(.+)$/;

function parseLines(lines:string[],page:number|null):ExtractedDraftQuestion[]{const result:ExtractedDraftQuestion[]=[];let current:{text:string;options:string[];marks:number;reference:string}|null=null;const flush=()=>{if(!current)return;result.push({questionType:current.options.length?"mcq":"short_answer",questionText:current.text.trim().toUpperCase(),options:current.options.length?current.options.map(v=>v.toUpperCase()):null,correctAnswer:"REVIEW REQUIRED",acceptedAnswers:null,explanation:"IMPORTED SUGGESTION - ADMINISTRATOR REVIEW REQUIRED.",difficulty:"intermediate",suggestedMarks:current.marks,tags:["IMPORT"],sourcePage:page,sourceReference:current.reference});current=null};for(const raw of lines){const line=raw.trim();if(!line)continue;const numbered=line.match(numberPattern);if(numbered){flush();const marks=numbered[2].match(marksPattern);current={text:marks?numbered[2].slice(0,marks.index).trim():numbered[2],options:[],marks:marks?Number(marks[1]):1,reference:`Question ${numbered[1]}`};continue}const option=line.match(optionPattern);if(option&&current){current.options.push(option[1]);continue}if(current){const marks=line.match(marksPattern);if(marks&&marks.index===0)current.marks=Number(marks[1]);else current.text+=` ${line}`}}flush();return result}

export async function extractQuestionsWithMetadata(bytes:Uint8Array,mimeType:string,filename:string):Promise<QuestionExtractionResult>{if(mimeType==="application/pdf"){const{PDFParse}=await import("pdf-parse"),parser=new PDFParse({data:bytes});try{const text=await parser.getText();if(text.pages.length>100)throw new Error("DOCUMENT_PAGE_LIMIT_EXCEEDED");const meaningful=text.pages.filter(p=>p.text.replace(/\s/g,"").length>=40).length,total=text.pages.reduce((sum,p)=>sum+p.text.replace(/\s/g,"").length,0),questions=text.pages.flatMap(p=>parseLines(p.text.split(/\r?\n/),p.num));if(total>=40&&meaningful>=Math.max(1,Math.ceil(text.pages.length*.35))&&questions.length)return{questions,model:"native-pdf"};return providerFallback(bytes,mimeType,filename)}finally{await parser.destroy()}}if(mimeType==="application/vnd.openxmlformats-officedocument.wordprocessingml.document"){const result=await mammoth.extractRawText({buffer:Buffer.from(bytes)}),questions=parseLines(result.value.split(/\r?\n/),null);if(!questions.length)throw new Error("NO_QUESTIONS_DETECTED");return{questions,model:"native-docx"}}if(mimeType==="image/jpeg"||mimeType==="image/png")return providerFallback(bytes,mimeType,filename);throw new Error("UNSUPPORTED_FILE_TYPE")}
export async function extractQuestions(bytes:Uint8Array,mimeType:string,filename:string){return(await extractQuestionsWithMetadata(bytes,mimeType,filename)).questions}
async function providerFallback(bytes:Uint8Array,mimeType:string,filename:string):Promise<QuestionExtractionResult>{const provider=await getDocumentExtractionProvider(),items=await provider.extractImageQuestions({bytes,mimeType,filename});if(!items.length)throw new Error("NO_QUESTIONS_DETECTED");return{model:provider.model,questions:items.map(q=>({questionType:q.questionType,questionText:q.questionText.trim().toUpperCase(),options:q.options?.map(v=>v.trim().toUpperCase())??null,correctAnswer:q.correctAnswer?.trim().toUpperCase()??"REVIEW REQUIRED",acceptedAnswers:q.acceptedAnswers?.map(v=>v.trim().toUpperCase())??null,explanation:q.explanation?.trim().toUpperCase()??"IMPORTED SUGGESTION - ADMINISTRATOR REVIEW REQUIRED.",difficulty:q.difficulty,suggestedMarks:q.suggestedMarks??1,tags:["IMPORT",q.visualDependency?"VISUAL_DEPENDENCY":"",...q.warnings.map(w=>`WARNING:${w}`)].filter(Boolean),sourcePage:q.sourcePage,sourceReference:q.sourceReference,associatedImage:q.associatedImage,associatedImageMimeType:q.associatedImageMimeType,extractionWarnings:q.warnings,visualDependency:q.visualDependency,visualDescription:q.visualDescription}))}}
