import assert from "node:assert/strict";
import test from "node:test";
import { DEFAULT_GEMINI_DOCUMENT_MODEL, GEMINI_DOCUMENT_API_VERSION, GeminiDocumentExtractionProvider, type GeminiLike } from "./gemini-document-extraction-provider";

const valid={questions:[{questionNumber:"1",questionText:"Choose the noun.",questionType:"mcq",options:["Run","Book"],proposedAnswer:"Book",acceptedAnswers:null,proposedExplanation:"Book names a thing.",marks:1,difficulty:"beginner",sourcePage:1,sourceReference:"Q1",visualDependency:false,visualDescription:null,warnings:[]},{questionNumber:"2",questionText:"Explain the sentence.",questionType:"short_answer",options:null,proposedAnswer:null,acceptedAnswers:null,proposedExplanation:null,marks:null,difficulty:"intermediate",sourcePage:2,sourceReference:"Q2",visualDependency:true,visualDescription:"A labelled diagram",warnings:["Answer not printed"]}]};
function client(value:string|undefined,error?:unknown,onInput?:(input:unknown)=>void):GeminiLike{return{interactions:{create:async(input)=>{onInput?.(input);if(error)throw error;return{id:"interaction-test",status:"completed",output_text:value}}}}}
test("Gemini structured output preserves questions and visual metadata",async()=>{let request:unknown;const provider=new GeminiDocumentExtractionProvider({client:client(JSON.stringify(valid),undefined,input=>{request=input}),model:"test-model"});const result=await provider.extractImageQuestions({bytes:new Uint8Array([1]),mimeType:"image/png",filename:"untrusted.png"});assert.equal(result.length,2);assert.equal(result[0].questionType,"mcq");assert.equal(result[1].visualDependency,true);assert.deepEqual(result[1].associatedImage,new Uint8Array([1]));assert.equal(provider.model,"test-model");const captured=request as{input:Array<{type:string;mime_type?:string}>;response_format:Array<{type:string;mime_type:string;schema:unknown}>};assert.equal(captured.input[0].type,"image");assert.equal(captured.input[0].mime_type,"image/png");assert.equal(captured.input[1].type,"text");assert.equal(captured.response_format.length,1);assert.equal(captured.response_format[0].type,"text");assert.equal(captured.response_format[0].mime_type,"application/json");assert.ok(captured.response_format[0].schema);const serialized=JSON.stringify(request);assert.equal(serialized.includes("responseMimeType"),false);assert.equal(serialized.includes("responseJsonSchema"),false)});
test("Gemini scanned PDF uses an Interactions document input",async()=>{let request:unknown;const provider=new GeminiDocumentExtractionProvider({client:client(JSON.stringify(valid),undefined,input=>{request=input})});await provider.extractImageQuestions({bytes:new Uint8Array([1]),mimeType:"application/pdf",filename:"scan.pdf"});const captured=request as{input:Array<{type:string;mime_type?:string}>};assert.equal(captured.input[0].type,"document");assert.equal(captured.input[0].mime_type,"application/pdf")});
test("Gemini document extraction uses the current default model",()=>{const provider=new GeminiDocumentExtractionProvider({client:client(JSON.stringify(valid))});assert.equal(provider.model,"gemini-3.6-flash");assert.equal(DEFAULT_GEMINI_DOCUMENT_MODEL,"gemini-3.6-flash")});
test("Gemini document extraction configures Interactions for API v1",()=>{let configuredVersion:string|undefined;new GeminiDocumentExtractionProvider({apiKey:"test-key",clientFactory:(options)=>{configuredVersion=options.httpOptions.apiVersion;return client(JSON.stringify(valid))}});assert.equal(configuredVersion,"v1");assert.equal(GEMINI_DOCUMENT_API_VERSION,"v1")});
test("Gemini document extraction accepts a strictly fenced JSON response",async()=>{const provider=new GeminiDocumentExtractionProvider({client:client(`\`\`\`json\n${JSON.stringify(valid)}\n\`\`\``)});const result=await provider.extractImageQuestions({bytes:new Uint8Array([1]),mimeType:"image/png",filename:"source.png"});assert.equal(result.length,2)});
test("malformed and schema-invalid responses are rejected",async()=>{for(const value of ["not-json",JSON.stringify({questions:[]})]){const provider=new GeminiDocumentExtractionProvider({client:client(value)});await assert.rejects(()=>provider.extractImageQuestions({bytes:new Uint8Array([1]),mimeType:"image/jpeg",filename:"x.jpg"}),/GEMINI_MALFORMED_RESPONSE/)}});
test("provider failures are safely classified",async()=>{for(const [error,code] of [[{status:429},"GEMINI_QUOTA_EXCEEDED"],[{status:401},"GEMINI_AUTH_FAILED"],[new Error("network"),"GEMINI_PROVIDER_UNAVAILABLE"]] as const){const provider=new GeminiDocumentExtractionProvider({client:client(undefined,error)});await assert.rejects(()=>provider.extractImageQuestions({bytes:new Uint8Array([1]),mimeType:"image/jpeg",filename:"x.jpg"}),new RegExp(code))}});
