import assert from "node:assert/strict";
import test from "node:test";
import { DEFAULT_GEMINI_DOCUMENT_MODEL, GeminiDocumentExtractionProvider, type GeminiLike } from "./gemini-document-extraction-provider";

const valid={questions:[{questionNumber:"1",questionText:"Choose the noun.",questionType:"mcq",options:["Run","Book"],proposedAnswer:"Book",acceptedAnswers:null,proposedExplanation:"Book names a thing.",marks:1,difficulty:"beginner",sourcePage:1,sourceReference:"Q1",visualDependency:false,visualDescription:null,warnings:[]},{questionNumber:"2",questionText:"Explain the sentence.",questionType:"short_answer",options:null,proposedAnswer:null,acceptedAnswers:null,proposedExplanation:null,marks:null,difficulty:"intermediate",sourcePage:2,sourceReference:"Q2",visualDependency:true,visualDescription:"A labelled diagram",warnings:["Answer not printed"]}]};
function client(value:string|undefined,error?:unknown):GeminiLike{return{models:{generateContent:async()=>{if(error)throw error;return{text:value}}}}}
test("Gemini structured output preserves questions and visual metadata",async()=>{const provider=new GeminiDocumentExtractionProvider({client:client(JSON.stringify(valid)),model:"test-model"});const result=await provider.extractImageQuestions({bytes:new Uint8Array([1]),mimeType:"image/png",filename:"untrusted.png"});assert.equal(result.length,2);assert.equal(result[0].questionType,"mcq");assert.equal(result[1].visualDependency,true);assert.deepEqual(result[1].associatedImage,new Uint8Array([1]));assert.equal(provider.model,"test-model")});
test("Gemini document extraction uses the current default model",()=>{const provider=new GeminiDocumentExtractionProvider({client:client(JSON.stringify(valid))});assert.equal(provider.model,"gemini-3.6-flash");assert.equal(DEFAULT_GEMINI_DOCUMENT_MODEL,"gemini-3.6-flash")});
test("malformed and schema-invalid responses are rejected",async()=>{for(const value of ["not-json",JSON.stringify({questions:[]})]){const provider=new GeminiDocumentExtractionProvider({client:client(value)});await assert.rejects(()=>provider.extractImageQuestions({bytes:new Uint8Array([1]),mimeType:"image/jpeg",filename:"x.jpg"}),/GEMINI_MALFORMED_RESPONSE/)}});
test("provider failures are safely classified",async()=>{for(const [error,code] of [[{status:429},"GEMINI_QUOTA_EXCEEDED"],[{status:401},"GEMINI_AUTH_FAILED"],[new Error("network"),"GEMINI_PROVIDER_UNAVAILABLE"]] as const){const provider=new GeminiDocumentExtractionProvider({client:client(undefined,error)});await assert.rejects(()=>provider.extractImageQuestions({bytes:new Uint8Array([1]),mimeType:"image/jpeg",filename:"x.jpg"}),new RegExp(code))}});
