import "server-only";

import { randomUUID } from "node:crypto";
import type { AuthProfile } from "@/features/auth/types/auth";
import { extractQuestionsWithMetadata, type ExtractedDraftQuestion } from "@/features/practice-work/services/document-extraction-service";
import { validateQuestionImportFile } from "@/features/practice-work/services/question-import-file";
import { normalizeQuestionText } from "@/features/practice-work/services/practice-work-service";
import { createClient } from "@/lib/supabase/server";

export class QuestionImportError extends Error { constructor(message:string,readonly generationId:string){super(message)} }
export async function importQuestions(profile:AuthProfile,file:File,metadata:{boardId:string;classId:string;subjectId:string;bookName?:string;chapter?:string;questionExamDate?:string;sourceFullMarks:number}){
  if(!profile.instituteId)throw new Error("PRACTICE_UNAUTHORIZED");const{bytes,mimeType,sha256}=await validateQuestionImportFile(file);
  const s=await createClient(),instituteId=profile.instituteId;await validateOwnership(s,instituteId,metadata);const{data:duplicate}=await s.from("practice_question_source_files").select("id").eq("institute_id",instituteId).eq("sha256",sha256).maybeSingle();if(duplicate)throw new Error("DUPLICATE_IMPORT");
  const sourceId=randomUUID(),safeName=file.name.replace(/[^A-Za-z0-9._-]/g,"_").slice(-180),path=`question-imports/${instituteId}/${sourceId}/${safeName}`;const upload=await s.storage.from("practice-work-private").upload(path,bytes,{contentType:mimeType,upsert:false});if(upload.error)throw upload.error;
  const{error:sourceError}=await s.from("practice_question_source_files").insert({id:sourceId,institute_id:instituteId,storage_path:path,original_filename:file.name,mime_type:mimeType,byte_size:file.size,sha256,status:"processing",created_by:profile.id});if(sourceError){await s.storage.from("practice-work-private").remove([path]);throw sourceError}
  const{data:batch,error:batchError}=await s.from("ai_question_generations").insert({institute_id:instituteId,source_type:"import",board_id:metadata.boardId,class_id:metadata.classId,subject_id:metadata.subjectId,book_name:metadata.bookName??null,chapter:metadata.chapter??null,source_full_marks:metadata.sourceFullMarks,question_exam_date:metadata.questionExamDate??null,source_file_id:sourceId,template_id:null,question_count_requested:1,difficulty:"intermediate",model:null,status:"processing",created_by:profile.id}).select("id").single();if(batchError)throw batchError;
  try{const extraction=await extractQuestionsWithMetadata(bytes,mimeType,file.name);await persistDrafts(s,profile,batch.id,sourceId,file.name,extraction.questions,extraction.model);return batch.id}catch(error){const code=error instanceof Error?error.message:"IMPORT_FAILED";await Promise.all([s.from("ai_question_generations").update({status:"failed",safe_error_code:code.slice(0,100)}).eq("id",batch.id),s.from("practice_question_source_files").update({status:"failed",safe_error_code:code.slice(0,100)}).eq("id",sourceId)]);throw new QuestionImportError(code,batch.id)}
}

export async function retryQuestionExtraction(profile:AuthProfile,generationId:string){if(!profile.instituteId)throw new Error("PRACTICE_UNAUTHORIZED");const s=await createClient();const{data:g,error}=await s.from("ai_question_generations").select("id,status,source_file_id,source_file:practice_question_source_files!inner(id,storage_path,original_filename,mime_type)").eq("id",generationId).eq("institute_id",profile.instituteId).eq("source_type","import").single();if(error||!g)throw new Error("IMPORT_NOT_FOUND");if(g.status!=="failed")throw new Error("IMPORT_RETRY_NOT_ALLOWED");const source=Array.isArray(g.source_file)?g.source_file[0]:g.source_file;if(!source)throw new Error("IMPORT_SOURCE_NOT_FOUND");const download=await s.storage.from("practice-work-private").download(source.storage_path);if(download.error)throw download.error;await Promise.all([s.from("ai_question_generations").update({status:"processing",safe_error_code:null}).eq("id",g.id).eq("institute_id",profile.instituteId),s.from("practice_question_source_files").update({status:"processing",safe_error_code:null}).eq("id",source.id).eq("institute_id",profile.instituteId)]);try{const extraction=await extractQuestionsWithMetadata(new Uint8Array(await download.data.arrayBuffer()),source.mime_type,source.original_filename);const{count}=await s.from("ai_generated_questions").select("id",{count:"exact",head:true}).eq("ai_generation_id",g.id);if(count)throw new Error("IMPORT_RETRY_WOULD_DUPLICATE");await persistDrafts(s,profile,g.id,source.id,source.original_filename,extraction.questions,extraction.model);return g.id}catch(error){const code=error instanceof Error?error.message:"IMPORT_FAILED";await Promise.all([s.from("ai_question_generations").update({status:"failed",safe_error_code:code.slice(0,100)}).eq("id",g.id),s.from("practice_question_source_files").update({status:"failed",safe_error_code:code.slice(0,100)}).eq("id",source.id)]);throw error}}

async function persistDrafts(s:Awaited<ReturnType<typeof createClient>>,profile:AuthProfile,generationId:string,sourceId:string,filename:string,drafts:ExtractedDraftQuestion[],model:string){const instituteId=profile.instituteId!;const normalized=drafts.map(q=>normalizeQuestionText(q.questionText));const{data:existing}=await s.from("question_bank").select("normalized_question_text").eq("institute_id",instituteId).in("normalized_question_text",normalized);const duplicates=new Set((existing??[]).map(v=>v.normalized_question_text));const rows=[];for(const q of drafts){let assetId:string|null=null;if(q.associatedImage&&q.associatedImageMimeType){assetId=randomUUID();const ext=q.associatedImageMimeType==="image/png"?"png":"jpg",assetPath=`question-assets/${instituteId}/${generationId}/${assetId}.${ext}`;const up=await s.storage.from("practice-work-private").upload(assetPath,q.associatedImage,{contentType:q.associatedImageMimeType});if(up.error)throw up.error;const asset=await s.from("practice_question_assets").insert({id:assetId,institute_id:instituteId,source_file_id:sourceId,storage_path:assetPath,mime_type:q.associatedImageMimeType,source_page:q.sourcePage,alt_text:(q.visualDescription??`QUESTION ASSET FROM ${filename}`).toUpperCase(),created_by:profile.id});if(asset.error)throw asset.error}rows.push({institute_id:instituteId,ai_generation_id:generationId,question_type:q.questionType,question_text:q.questionText,options:q.options,correct_answer:q.correctAnswer,accepted_answers:q.acceptedAnswers,answer_explanation:q.explanation,difficulty:q.difficulty,suggested_marks:q.suggestedMarks,tags:[...q.tags,...(q.extractionWarnings??[]).map(w=>`WARNING:${w}`)],source_page:q.sourcePage,source_reference:q.sourceReference,source_asset_id:assetId,duplicate_warning:duplicates.has(normalizeQuestionText(q.questionText))})}const inserted=await s.from("ai_generated_questions").insert(rows);if(inserted.error)throw inserted.error;await Promise.all([s.from("ai_question_generations").update({status:"review_required",model,generated_count:rows.length,question_count_requested:rows.length,safe_error_code:null}).eq("id",generationId),s.from("practice_question_source_files").update({status:"review_required",safe_error_code:null}).eq("id",sourceId)])}

async function validateOwnership(s:Awaited<ReturnType<typeof createClient>>,instituteId:string,m:{boardId:string;classId:string;subjectId:string}){const results=await Promise.all([s.from("boards").select("id").eq("id",m.boardId).eq("institute_id",instituteId).maybeSingle(),s.from("academic_classes").select("id").eq("id",m.classId).eq("institute_id",instituteId).maybeSingle(),s.from("subjects").select("id").eq("id",m.subjectId).eq("institute_id",instituteId).maybeSingle()]);if(results.some(r=>r.error||!r.data))throw new Error("PRACTICE_REFERENCE_INVALID")}
