"use client";

import { useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { importPublicHolidayAction, saveHolidaySettingsAction, setPublicHolidayObservationAction } from "@/features/learning-planner/actions/holiday-actions";
import type { HolidaySettings, PlannerOption, PublicHoliday } from "@/features/learning-planner/types/learning-planner";

const STATES=[["IN-AN","Andaman and Nicobar Islands"],["IN-AP","Andhra Pradesh"],["IN-AR","Arunachal Pradesh"],["IN-AS","Assam"],["IN-BR","Bihar"],["IN-CH","Chandigarh"],["IN-CT","Chhattisgarh"],["IN-DL","Delhi"],["IN-GA","Goa"],["IN-GJ","Gujarat"],["IN-HR","Haryana"],["IN-HP","Himachal Pradesh"],["IN-JH","Jharkhand"],["IN-KA","Karnataka"],["IN-KL","Kerala"],["IN-LA","Ladakh"],["IN-MP","Madhya Pradesh"],["IN-MH","Maharashtra"],["IN-MN","Manipur"],["IN-ML","Meghalaya"],["IN-MZ","Mizoram"],["IN-NL","Nagaland"],["IN-OD","Odisha"],["IN-PY","Puducherry"],["IN-PB","Punjab"],["IN-RJ","Rajasthan"],["IN-TN","Tamil Nadu"],["IN-TG","Telangana"],["IN-TR","Tripura"],["IN-UP","Uttar Pradesh"],["IN-UT","Uttarakhand"],["IN-WB","West Bengal"]] as const;

export function HolidaySettingsManager({settings,holidays,branches,providerAvailable}:{settings:HolidaySettings;holidays:PublicHoliday[];branches:PlannerOption[];providerAvailable:boolean}){
  const router=useRouter(); const[pending,start]=useTransition(); const[feedback,setFeedback]=useState<string|null>(null); const[branchId,setBranchId]=useState("");
  const run=(operation:()=>Promise<{status:"success"|"error";message:string}>)=>start(async()=>{const result=await operation();setFeedback(result.message);if(result.status==="success")router.refresh();});
  const importHoliday=(holiday:PublicHoliday,observedAsHoliday:boolean)=>run(()=>importPublicHolidayAction({externalId:holiday.externalId,provider:holiday.provider,name:holiday.name,date:holiday.date,scope:holiday.scope,subdivisionCode:holiday.subdivisionCode??undefined,branchId:branchId||undefined,observedAsHoliday}));
  return <div className="space-y-6">
    <Card><CardHeader><CardTitle>India Holiday Settings</CardTitle></CardHeader><CardContent><form action={form=>run(()=>saveHolidaySettingsAction({stateCode:form.get("stateCode"),showNationalHolidays:form.get("showNationalHolidays")==="on",showStateHolidays:form.get("showStateHolidays")==="on"}))} className="grid gap-4 md:grid-cols-2"><label className="text-sm font-medium">Country<select disabled className="mt-1 h-10 w-full rounded-xl border bg-muted px-3"><option>India (IN)</option></select></label><label className="text-sm font-medium">State / Union Territory<select name="stateCode" defaultValue={settings.stateCode??""} className="mt-1 h-10 w-full rounded-xl border bg-card px-3"><option value="">Not selected</option>{STATES.map(([code,name])=><option key={code} value={code}>{name}</option>)}</select></label><label className="flex items-center gap-2 text-sm"><input name="showNationalHolidays" type="checkbox" defaultChecked={settings.showNationalHolidays}/>Show India national holidays</label><label className="flex items-center gap-2 text-sm"><input name="showStateHolidays" type="checkbox" defaultChecked={settings.showStateHolidays}/>Show State/UT holidays</label><div className="md:col-span-2"><Button disabled={pending}>Save Settings</Button></div></form></CardContent></Card>
    {branches.length?<Card><CardContent className="p-4"><label className="text-sm font-medium">Import scope<select value={branchId} onChange={event=>setBranchId(event.target.value)} className="mt-1 h-10 w-full rounded-xl border bg-card px-3 sm:max-w-md"><option value="">Institute-wide</option>{branches.map(branch=><option key={branch.id} value={branch.id}>{branch.label}</option>)}</select></label></CardContent></Card>:null}
    {!providerAvailable?<p role="status" className="rounded-xl border border-amber-300 bg-amber-50 p-3 text-sm text-amber-900">Public holiday preview is temporarily unavailable. Durable holidays and schedule generation are unaffected.</p>:null}
    <div className="space-y-3"><h2 className="text-xl font-semibold">Holiday Preview and Policy</h2>{holidays.length===0?<Card><CardContent className="p-8 text-center text-muted-foreground">No public holidays are available for this year and configuration.</CardContent></Card>:holidays.map(holiday=><Card key={holiday.id}><CardContent className="flex flex-col gap-4 p-4 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex flex-wrap gap-2"><strong>{holiday.name}</strong><Badge variant="outline">{holiday.scope==="national"?"India Holiday":"State Holiday"}</Badge>{holiday.source==="external"?<Badge variant="secondary">Display only</Badge>:holiday.observedAsHoliday?<Badge>Non-working</Badge>:<Badge variant="outline">Classes held</Badge>}</div><p className="mt-1 text-sm text-muted-foreground">{holiday.date}{holiday.subdivisionCode?` · ${holiday.subdivisionCode}`:""}{holiday.branchId?" · Branch-specific":""}</p></div><div className="flex flex-wrap gap-2">{holiday.source==="external"?<><Button size="sm" disabled={pending} onClick={()=>importHoliday(holiday,true)}>Import as Non-working</Button><Button size="sm" variant="outline" disabled={pending} onClick={()=>importHoliday(holiday,false)}>Classes Held</Button></>:<Button size="sm" variant="outline" disabled={pending} onClick={()=>run(()=>setPublicHolidayObservationAction({id:holiday.id,observedAsHoliday:!holiday.observedAsHoliday}))}>{holiday.observedAsHoliday?"Override: Classes Held":"Treat as Non-working"}</Button>}</div></CardContent></Card>)}</div>
    {feedback?<p role="status" className="rounded-xl border p-3 text-sm">{feedback}</p>:null}
  </div>;
}
