"use client";
import { useTransition } from "react";
import { useRouter } from "next/navigation";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card,CardContent } from "@/components/ui/card";
import { markPlannerNotificationReadAction } from "@/features/learning-planner/actions/notification-actions";
import type { PlannerMessageOutboxItem,PlannerNotification } from "@/features/learning-planner/types/learning-planner";
export function NotificationList({notifications,outbox=[]}:{notifications:PlannerNotification[];outbox?:PlannerMessageOutboxItem[]}){const[pending,start]=useTransition();const router=useRouter();return <div className="space-y-6"><section className="space-y-3"><h2 className="text-xl font-semibold">In-app and Email Notifications</h2>{notifications.length===0?<Card><CardContent className="p-8 text-center text-muted-foreground">You have no Learning Planner notifications.</CardContent></Card>:notifications.map(item=><Card key={item.recipientId}><CardContent className="flex flex-col gap-3 p-5 sm:flex-row sm:justify-between"><div><div className="flex items-center gap-2"><p className="font-semibold">{item.title}</p><Badge>{item.priority}</Badge></div><p className="mt-1 text-sm text-muted-foreground">{item.message}</p><p className="mt-2 text-xs text-muted-foreground">{new Date(item.createdAt).toLocaleString()} · {item.deliveryChannel.replaceAll("_"," ")}</p></div>{!item.readAt&&<Button size="sm" variant="outline" disabled={pending} onClick={()=>start(async()=>{await markPlannerNotificationReadAction({recipientId:item.recipientId});router.refresh();})}>Mark read</Button>}</CardContent></Card>)}</section><section className="space-y-3"><div><h2 className="text-xl font-semibold">WhatsApp Outbox</h2><p className="text-sm text-muted-foreground">Planner changes succeed independently of provider delivery.</p></div>{outbox.length===0?<Card><CardContent className="p-8 text-center text-muted-foreground">No Planner WhatsApp messages queued.</CardContent></Card>:outbox.map(item=><Card key={item.id}><CardContent className="flex items-center justify-between gap-3 p-4"><div><p className="font-medium">{item.eventTitle}</p><p className="text-xs text-muted-foreground">{item.messageType.replaceAll("_"," ")} · {item.recipientRole} · {new Date(item.createdAt).toLocaleString()}</p></div><Badge variant="outline">{item.status.replaceAll("_"," ")}</Badge></CardContent></Card>)}</section></div>}
