"use server";
import { revalidatePath } from "next/cache";
import { cancelEventOptionsSchema, completeEventSchema, recurringOccurrenceActionSchema, scheduleEventSchema } from "@/features/learning-planner/schemas/event-schema";
import { rescheduleEventSchema } from "@/features/learning-planner/schemas/reschedule-schema";
import { cancelScheduleEventWithOptions, completeScheduleEvent, createScheduleEvent, persistRecurringOccurrenceException, rescheduleScheduleEvent, schedulePendingReplacement } from "@/features/learning-planner/services/event-service";
import type { EventPlannerActionResult as PlannerActionResult } from "@/features/learning-planner/types/learning-planner";
import { requireRole } from "@/lib/auth/services/auth-service";
import { DASHBOARD_ROLES } from "@/lib/navigation";
function refresh() { ["/learning-planner", "/learning-planner/calendar", "/learning-planner/events", "/learning-planner/history", "/student/dashboard", "/student/schedule"].forEach((path) => revalidatePath(path)); }
function databaseMessage(error: unknown) { const value = error instanceof Error ? error.message : ""; if (value.includes("PLANNER_BATCH_CONFLICT")) return "This Batch already has an overlapping event."; if (value.includes("PLANNER_ROOM_CONFLICT")) return "This Room already has an overlapping event."; if (value.includes("PLANNER_REFERENCE_INVALID")) return "A selected Academic Year, Batch, Subject, or Branch is unavailable."; if (value.includes("PLANNER_STATE_INVALID")) return "This event can no longer be changed."; return "We could not update this Schedule Event."; }
export async function createScheduleEventAction(input: unknown): Promise<PlannerActionResult> { const parsed = scheduleEventSchema.safeParse(input); if (!parsed.success) return { status: "error", message: "Correct the highlighted fields.", fieldErrors: parsed.error.flatten().fieldErrors }; const profile = await requireRole(DASHBOARD_ROLES); try { const result = await createScheduleEvent(profile, parsed.data);if(result.status==="conflict")return{status:"conflict",message:"This event overlaps another Batch.",conflicts:result.conflicts}; refresh(); return { status: "success", message: result.whatsappStatus==="queue_failed"?"Event saved, but WhatsApp could not be queued.":result.whatsappStatus==="not_configured"?"Event saved. WhatsApp is not configured; the message remains queued.":"Schedule Event created.", id:result.id }; } catch (error) { return { status: "error", message: databaseMessage(error) }; } }
export async function rescheduleScheduleEventAction(input: unknown): Promise<PlannerActionResult> { const parsed = rescheduleEventSchema.safeParse(input); if (!parsed.success) return { status: "error", message: "Enter a valid new date, time, and reason.", fieldErrors: parsed.error.flatten().fieldErrors }; await requireRole(DASHBOARD_ROLES); try { const result = await rescheduleScheduleEvent(parsed.data);if(result.status==="conflict")return{status:"conflict",message:"This event overlaps another Batch.",conflicts:result.conflicts}; refresh(); return { status: "success", message: "Schedule Event rescheduled.", id:result.id }; } catch (error) { return { status: "error", message: databaseMessage(error) }; } }
export async function cancelScheduleEventAction(input: unknown): Promise<PlannerActionResult> { const parsed = cancelEventOptionsSchema.safeParse(input); if (!parsed.success) return { status: "error", message: "Enter a cancellation reason.", fieldErrors: parsed.error.flatten().fieldErrors }; await requireRole(DASHBOARD_ROLES); try { const whatsapp=await cancelScheduleEventWithOptions(parsed.data); refresh(); return { status: "success", message: whatsapp==="queue_failed"?"Class cancelled, but WhatsApp could not be queued.":parsed.data.reschedulePending?"Class cancelled. Reschedule details are pending.":"Schedule Event cancelled." }; } catch (error) { return { status: "error", message: databaseMessage(error) }; } }
export async function schedulePendingReplacementAction(input:unknown):Promise<PlannerActionResult>{const parsed=rescheduleEventSchema.safeParse(input);if(!parsed.success)return{status:"error",message:"Enter a valid replacement date, time and reason.",fieldErrors:parsed.error.flatten().fieldErrors};await requireRole(DASHBOARD_ROLES);try{const result=await schedulePendingReplacement(parsed.data);if(result.status==="conflict")return{status:"conflict",message:"This reschedule overlaps another Batch.",conflicts:result.conflicts};refresh();return{status:"success",message:result.whatsappStatus==="queue_failed"?"Reschedule saved, but WhatsApp could not be queued.":"Rescheduled class scheduled.",id:result.id};}catch(error){return{status:"error",message:databaseMessage(error)};}}
export async function persistRecurringOccurrenceExceptionAction(input:unknown):Promise<PlannerActionResult>{const parsed=recurringOccurrenceActionSchema.safeParse(input);if(!parsed.success)return{status:"error",message:"Enter valid occurrence details.",fieldErrors:parsed.error.flatten().fieldErrors};await requireRole(DASHBOARD_ROLES);try{const result=await persistRecurringOccurrenceException(parsed.data);if(result.status==="conflict")return{status:"conflict",message:"This rescheduled class overlaps another Batch.",conflicts:result.conflicts};refresh();return{status:"success",message:parsed.data.action==="cancel"?"Class cancellation recorded.":"Class rescheduled and history recorded.",id:result.id};}catch(error){return{status:"error",message:databaseMessage(error)};}}
export async function completeScheduleEventAction(input: unknown): Promise<PlannerActionResult> { const parsed = completeEventSchema.safeParse(input); if (!parsed.success) return { status: "error", message: "Invalid Schedule Event." }; await requireRole(DASHBOARD_ROLES); try { await completeScheduleEvent(parsed.data); refresh(); return { status: "success", message: "Schedule Event completed." }; } catch (error) { return { status: "error", message: databaseMessage(error) }; } }
