"use server";
import { revalidatePath } from "next/cache";
import { cancelEventSchema, completeEventSchema, scheduleEventSchema } from "@/features/learning-planner/schemas/event-schema";
import { rescheduleEventSchema } from "@/features/learning-planner/schemas/reschedule-schema";
import { cancelScheduleEvent, completeScheduleEvent, createScheduleEvent, rescheduleScheduleEvent } from "@/features/learning-planner/services/event-service";
import type { PlannerActionResult } from "@/features/learning-planner/types/learning-planner";
import { requireRole } from "@/lib/auth/services/auth-service";
import { DASHBOARD_ROLES } from "@/lib/navigation";
function refresh() { ["/learning-planner", "/learning-planner/calendar", "/learning-planner/events", "/learning-planner/history"].forEach((path) => revalidatePath(path)); }
function databaseMessage(error: unknown) { const value = error instanceof Error ? error.message : ""; if (value.includes("PLANNER_BATCH_CONFLICT")) return "This Batch already has an overlapping event."; if (value.includes("PLANNER_ROOM_CONFLICT")) return "This Room already has an overlapping event."; if (value.includes("PLANNER_REFERENCE_INVALID")) return "A selected Academic Year, Batch, Subject, or Branch is unavailable."; if (value.includes("PLANNER_STATE_INVALID")) return "This event can no longer be changed."; return "We could not update this Schedule Event."; }
export async function createScheduleEventAction(input: unknown): Promise<PlannerActionResult> { const parsed = scheduleEventSchema.safeParse(input); if (!parsed.success) return { status: "error", message: "Correct the highlighted fields.", fieldErrors: parsed.error.flatten().fieldErrors }; const profile = await requireRole(DASHBOARD_ROLES); try { const id = await createScheduleEvent(profile, parsed.data); refresh(); return { status: "success", message: "Schedule Event created.", id }; } catch (error) { return { status: "error", message: databaseMessage(error) }; } }
export async function rescheduleScheduleEventAction(input: unknown): Promise<PlannerActionResult> { const parsed = rescheduleEventSchema.safeParse(input); if (!parsed.success) return { status: "error", message: "Enter a valid new date, time, and reason.", fieldErrors: parsed.error.flatten().fieldErrors }; await requireRole(DASHBOARD_ROLES); try { const id = await rescheduleScheduleEvent(parsed.data); refresh(); return { status: "success", message: "Schedule Event rescheduled.", id }; } catch (error) { return { status: "error", message: databaseMessage(error) }; } }
export async function cancelScheduleEventAction(input: unknown): Promise<PlannerActionResult> { const parsed = cancelEventSchema.safeParse(input); if (!parsed.success) return { status: "error", message: "Enter a cancellation reason.", fieldErrors: parsed.error.flatten().fieldErrors }; await requireRole(DASHBOARD_ROLES); try { await cancelScheduleEvent(parsed.data); refresh(); return { status: "success", message: "Schedule Event cancelled." }; } catch (error) { return { status: "error", message: databaseMessage(error) }; } }
export async function completeScheduleEventAction(input: unknown): Promise<PlannerActionResult> { const parsed = completeEventSchema.safeParse(input); if (!parsed.success) return { status: "error", message: "Invalid Schedule Event." }; await requireRole(DASHBOARD_ROLES); try { await completeScheduleEvent(parsed.data); refresh(); return { status: "success", message: "Schedule Event completed." }; } catch (error) { return { status: "error", message: databaseMessage(error) }; } }
