"use server";
import { revalidatePath } from "next/cache";
import { createClassSchedule, deactivateClassSchedule, updateClassSchedule } from "@/features/learning-planner/services/schedule-service";
import { classScheduleSchema, deactivateClassScheduleSchema, updateClassScheduleSchema } from "@/features/learning-planner/schemas/schedule-schema";
import type { PlannerActionResult } from "@/features/learning-planner/types/learning-planner";
import { requireRole } from "@/lib/auth/services/auth-service";
import { DASHBOARD_ROLES } from "@/lib/navigation";
const message = (error: unknown) => error instanceof Error && error.message.includes("PLANNER_REFERENCE_INVALID") ? "A selected Academic Year, Batch, Subject, or Branch is unavailable." : "We could not save this Class Schedule.";
export async function createClassScheduleAction(input: unknown): Promise<PlannerActionResult> { const parsed = classScheduleSchema.safeParse(input); if (!parsed.success) return { status: "error", message: "Correct the highlighted fields.", fieldErrors: parsed.error.flatten().fieldErrors }; const profile = await requireRole(DASHBOARD_ROLES); try { const id = await createClassSchedule(profile, parsed.data); revalidatePath("/learning-planner/schedules"); return { status: "success", message: "Class Schedule created.", id }; } catch (error) { return { status: "error", message: message(error) }; } }
export async function updateClassScheduleAction(input: unknown): Promise<PlannerActionResult> { const parsed = updateClassScheduleSchema.safeParse(input); if (!parsed.success) return { status: "error", message: "Correct the highlighted fields.", fieldErrors: parsed.error.flatten().fieldErrors }; const profile = await requireRole(DASHBOARD_ROLES); try { await updateClassSchedule(profile, parsed.data); revalidatePath("/learning-planner/schedules"); return { status: "success", message: "Class Schedule updated." }; } catch (error) { return { status: "error", message: message(error) }; } }
export async function deactivateClassScheduleAction(input: unknown): Promise<PlannerActionResult> { const parsed = deactivateClassScheduleSchema.safeParse(input); if (!parsed.success) return { status: "error", message: "Invalid Class Schedule." }; const profile = await requireRole(DASHBOARD_ROLES); try { await deactivateClassSchedule(profile, parsed.data.id); revalidatePath("/learning-planner/schedules"); return { status: "success", message: "Class Schedule deactivated." }; } catch { return { status: "error", message: "We could not deactivate this Class Schedule." }; } }
