"use server";
import { revalidatePath } from "next/cache";
import { unstable_rethrow } from "next/navigation";
import { aiGenerationSchema,draftQuestionEditSchema,generationReviewSchema } from "@/features/practice-work/schemas/ai-generation-schema";
import { processQuestionImportSchema, questionImportUploadSchema } from "@/features/practice-work/schemas/question-import-schema";
import { questionIdSchema,questionSchema,questionTemplateSchema } from "@/features/practice-work/schemas/question-schema";
import { assignmentSchema,attemptStartSchema,attemptSubmitSchema,practiceSetIdSchema,practiceSetSchema,retrySchema } from "@/features/practice-work/schemas/practice-set-schema";
import { generateQuestionsWithAi,reviewGeneratedQuestions,updateGeneratedQuestion } from "@/features/practice-work/services/ai-question-service";
import { authorizeQuestionImportUpload, processUploadedQuestions, QuestionImportError, retryQuestionExtraction } from "@/features/practice-work/services/question-import-service";
import { createRetry,startAttempt,submitAttempt } from "@/features/practice-work/services/practice-attempt-service";
import { assignPracticeSet,createPracticeSet,createRecommendedTemplates,publishPracticeSet,saveBankQuestion,saveTemplate,setTemplateActive } from "@/features/practice-work/services/practice-work-service";
import type { PracticeActionResult,AttemptSession,SubmitAttemptResult } from "@/features/practice-work/types/practice-work";
import { requireActionRole, requireRole } from "@/lib/auth/services/auth-service";
import { DASHBOARD_ROLES } from "@/lib/navigation";
const paths=["/practice-work","/practice-work/question-bank","/practice-work/templates","/practice-work/generations","/practice-work/sets","/practice-work/assignments"];
const refresh=()=>paths.forEach(p=>revalidatePath(p));
const safeServerError=(error:unknown)=>{const value=error as {name?:unknown;message?:unknown;code?:unknown;status?:unknown;statusCode?:unknown;digest?:unknown};return{name:typeof value?.name==="string"?value.name:"UnknownError",message:typeof value?.message==="string"?value.message.slice(0,300):"Unknown failure",code:typeof value?.code==="string"||typeof value?.code==="number"?value.code:null,status:typeof value?.status==="number"?value.status:typeof value?.statusCode==="number"?value.statusCode:null,digest:typeof value?.digest==="string"?value.digest.slice(0,200):null}};
export async function createRecommendedTemplatesAction():Promise<PracticeActionResult>{try{const profile=await requireRole(DASHBOARD_ROLES);await createRecommendedTemplates(profile);refresh();return{status:"success",message:"Recommended Templates are ready."}}catch{return{status:"error",message:"We could not create the recommended Templates."}}}
const fail=(error:unknown,fallback:string)=>{const m=error instanceof Error?error.message:"";return m.includes("GEMINI_GENERATION_NOT_CONFIGURED")?"Gemini generation is not configured.":m.includes("GEMINI_GENERATION_REQUEST_REJECTED")?"Gemini request was rejected.":m.includes("GEMINI_GENERATION_AUTH_FAILED")?"Gemini authentication failed.":m.includes("GEMINI_GENERATION_PERMISSION_DENIED")?"Gemini permission denied.":m.includes("GEMINI_GENERATION_MODEL_UNAVAILABLE")?"Gemini model is unavailable.":m.includes("GEMINI_GENERATION_QUOTA_EXCEEDED")?"Gemini quota or rate limit reached.":m.includes("GEMINI_GENERATION_TIMEOUT")?"Gemini generation timed out.":m.includes("GEMINI_GENERATION_INVALID_RESPONSE")?"Gemini returned an invalid response.":m.includes("GEMINI_GENERATION_SERVICE_UNAVAILABLE")||m.includes("GEMINI_GENERATION_PROVIDER_UNAVAILABLE")?"Gemini service is temporarily unavailable.":m.startsWith("STORAGE_UPLOAD_AUTH:")?`Upload authorization failed: ${m.slice(20)}`:m.startsWith("STORAGE_DOWNLOAD:")?`Uploaded file could not be read: ${m.slice(17)}`:m.includes("IMPORT_PATH_INVALID")?"The uploaded file path is not authorized for this institute.":m.includes("FILE_SIZE_MISMATCH")||m.includes("FILE_HASH_MISMATCH")?"The uploaded file failed integrity validation.":m.includes("LEGACY_DOC")?"Legacy .doc files are not supported. Save the document as DOCX or PDF.":m.includes("UNSUPPORTED_FILE")?"Unsupported file type.":m.includes("FILE_TOO_LARGE")?"File is too large. Maximum size is 15 MB.":m.includes("MALFORMED")||m.includes("FILE_TYPE_MISMATCH")?"The document could not be parsed or its file type does not match.":m.includes("GEMINI_NOT_CONFIGURED")?"Gemini document extraction is not configured.":m.includes("GEMINI_QUOTA")?"Gemini document extraction is temporarily unavailable because its quota was reached.":m.includes("GEMINI_TIMEOUT")||m.includes("GEMINI_PROVIDER")?"Gemini document extraction is temporarily unavailable. Retry this extraction.":m.includes("GEMINI_AUTH")?"Gemini document extraction configuration could not be authenticated.":m.includes("NO_QUESTIONS")?"No questions could be detected.":m.includes("GENERATED_MARKS_MISMATCH")?"Generated marks total does not equal Full Marks.":m.includes("DUPLICATE_IMPORT")?"This exact source file has already been imported.":m.includes("DUPLICATE")?"A similar Question already exists. Review the duplicate warning before overriding.":m.includes("TARGET_MARKS")?"Question marks do not match the Target Total Marks.":m.includes("PRACTICE_MAX_ATTEMPTS")?"The maximum number of attempts has been reached.":m.includes("PRACTICE_ANSWERS_INCOMPLETE")?"Answer every Question before submitting.":fallback};
export async function saveTemplateAction(input:unknown):Promise<PracticeActionResult<{id:string}>>{const p=questionTemplateSchema.safeParse(input);if(!p.success)return{status:"error",message:"Correct the Template fields.",fieldErrors:p.error.flatten().fieldErrors};try{const profile=await requireRole(DASHBOARD_ROLES);const id=await saveTemplate(profile,p.data);refresh();return{status:"success",message:"Question Template saved.",data:{id}}}catch(e){return{status:"error",message:fail(e,"We could not save the Question Template.")}}}
export async function setTemplateActiveAction(input:unknown):Promise<PracticeActionResult>{const p=questionIdSchema.extend({isActive:questionTemplateSchema.shape.supportsOptions}).safeParse(input);if(!p.success)return{status:"error",message:"Invalid Template."};try{await requireRole(DASHBOARD_ROLES).then(profile=>setTemplateActive(profile,p.data.id,p.data.isActive));refresh();return{status:"success",message:`Question Template ${p.data.isActive?"reactivated":"deactivated"}.`}}catch(e){return{status:"error",message:fail(e,"We could not update the Template." )}}}
export async function saveQuestionAction(input:unknown):Promise<PracticeActionResult<{id:string}>>{const p=questionSchema.safeParse(input);if(!p.success)return{status:"error",message:"Correct the Question fields.",fieldErrors:p.error.flatten().fieldErrors};try{const profile=await requireRole(DASHBOARD_ROLES);const id=await saveBankQuestion(profile,{id:p.data.id,boardId:p.data.boardId??null,classId:p.data.classId??null,bookName:p.data.bookName??null,chapter:p.data.chapter??null,skill:p.data.skill??null,topic:p.data.topic??null,subtopic:p.data.subtopic??null,templateId:p.data.templateId??null,questionType:p.data.questionType,questionText:p.data.questionText,options:p.data.options??null,correctAnswer:p.data.correctAnswer,acceptedAnswers:p.data.acceptedAnswers??null,answerExplanation:p.data.answerExplanation??null,difficulty:p.data.difficulty,suggestedMarks:p.data.suggestedMarks??null});refresh();return{status:"success",message:"Question saved to the Question Bank.",data:{id}}}catch(e){return{status:"error",message:fail(e,"We could not save this Question.")}}}
export async function generateQuestionsAction(input:unknown):Promise<PracticeActionResult<{generationId:string}>>{const p=aiGenerationSchema.safeParse(input);if(!p.success)return{status:"error",message:"Correct the generation fields.",fieldErrors:p.error.flatten().fieldErrors};try{const profile=await requireActionRole(DASHBOARD_ROLES);const generationId=await generateQuestionsWithAi(profile,p.data);refresh();return{status:"success",message:"Questions generated for review. Nothing was added to the Question Bank.",data:{generationId}}}catch(e){unstable_rethrow(e);console.error("Practice question generation action failed",{stage:"GENERATION_ACTION",...safeServerError(e)});return{status:"error",message:fail(e,"AI generation failed. Please try again.")}}}
export async function reviewGeneratedQuestionsAction(input:unknown):Promise<PracticeActionResult>{const p=generationReviewSchema.safeParse(input);if(!p.success)return{status:"error",message:"Select Questions to review."};try{const profile=await requireRole(DASHBOARD_ROLES);const r=await reviewGeneratedQuestions(profile,p.data);refresh();return{status:"success",message:`Review saved: ${r.approved} approved, ${r.rejected} rejected.`}}catch(e){return{status:"error",message:fail(e,"We could not save the review.")}}}
export async function authorizeQuestionImportUploadAction(input:unknown):Promise<PracticeActionResult<{sourceId:string;storagePath:string;uploadToken:string}>>{let stage="AUTH_ACTION_START";console.info("AUTH_ACTION_START");try{const profile=await requireActionRole(DASHBOARD_ROLES);stage="AUTH_PROFILE_RESOLVED";console.info("AUTH_PROFILE_RESOLVED",{role:profile.role,instituteScope:"authenticated-profile"});const parsed=questionImportUploadSchema.safeParse(input);if(!parsed.success){console.warn("AUTH_ACTION_FAILED",{stage:"UPLOAD_INPUT_VALIDATED",name:"ValidationError",message:"Invalid upload metadata"});return{status:"error",message:"Upload authorization failed: select a supported source file up to 15 MB."}}stage="UPLOAD_INPUT_VALIDATED";console.info("UPLOAD_INPUT_VALIDATED",{mimeType:parsed.data.mimeType,byteSize:parsed.data.byteSize});stage="SIGNED_UPLOAD_REQUEST";console.info("SIGNED_UPLOAD_REQUEST",{bucket:"practice-work-private",pathPrefix:"question-imports/<institute>/<source-id>/"});const data=await authorizeQuestionImportUpload(profile,parsed.data);stage="SIGNED_UPLOAD_CREATED";console.info("SIGNED_UPLOAD_CREATED",{role:profile.role,instituteScope:"authenticated-profile",pathPrefix:"question-imports/<institute>/<source-id>/"});return{status:"success",message:"Upload authorized.",data:{sourceId:data.sourceId,storagePath:data.storagePath,uploadToken:data.uploadToken}}}catch(e){unstable_rethrow(e);const details=safeServerError(e),message=fail(e,"Upload authorization failed.");console.error("AUTH_ACTION_FAILED",{stage,...details});return{status:"error",message:`Upload authorization failed: ${message.replace(/^Upload authorization failed:\s*/,"")}`}}}
export async function processUploadedQuestionImportAction(input:unknown):Promise<PracticeActionResult<{generationId:string}>>{const parsed=processQuestionImportSchema.safeParse(input);if(!parsed.success){console.error("Practice import processing rejected",{stage:"schema_validation",fields:Object.keys(parsed.error.flatten().fieldErrors)});return{status:"error",message:"Document validation failed: complete the required import metadata.",fieldErrors:parsed.error.flatten().fieldErrors}}try{const profile=await requireRole(DASHBOARD_ROLES),generationId=await processUploadedQuestions(profile,parsed.data);refresh();return{status:"success",message:"Review required. Questions were extracted for Administrator review.",data:{generationId}}}catch(e){const message=fail(e,"The uploaded document could not be processed."),code=e instanceof Error?e.message.split(":",1)[0]:"UNKNOWN",stage=code.startsWith("GEMINI_")?"gemini_extraction":code.startsWith("STORAGE_")?"storage":code.includes("PATH")?"path_validation":code.includes("MIME")||code.includes("FILE_")||code.includes("MALFORMED")?"document_validation":code.includes("DUPLICATE")?"duplicate_detection":"processing";console.error("Practice import processing failed",{stage,code,message,generationId:e instanceof QuestionImportError?e.generationId:null});const prefix=stage==="gemini_extraction"?"Gemini extraction failed":stage==="document_validation"||stage==="path_validation"?"Document validation failed":stage==="storage"?"Storage upload failed":"Document processing failed";return{status:"error",message:`${prefix}: ${message}`,data:e instanceof QuestionImportError?{generationId:e.generationId}:undefined}}}
export async function retryQuestionExtractionAction(input:{generationId:string}):Promise<PracticeActionResult<{generationId:string}>>{const parsed=questionIdSchema.safeParse({id:input.generationId});if(!parsed.success)return{status:"error",message:"Invalid extraction."};try{const profile=await requireRole(DASHBOARD_ROLES),generationId=await retryQuestionExtraction(profile,parsed.data.id);refresh();return{status:"success",message:"Questions extracted for Administrator review.",data:{generationId}}}catch(e){return{status:"error",message:fail(e,"Extraction retry failed. Please try again.")}}}
export async function updateGeneratedQuestionAction(input:unknown):Promise<PracticeActionResult>{const p=draftQuestionEditSchema.safeParse(input);if(!p.success)return{status:"error",message:"Correct the draft Question fields.",fieldErrors:p.error.flatten().fieldErrors};try{const profile=await requireRole(DASHBOARD_ROLES);await updateGeneratedQuestion(profile,{id:p.data.id,questionType:p.data.questionType,questionText:p.data.questionText.toUpperCase(),options:p.data.options?.map(v=>v.toUpperCase())??null,correctAnswer:p.data.correctAnswer,acceptedAnswers:p.data.acceptedAnswers?.map(v=>v.toUpperCase())??null,explanation:p.data.explanation.toUpperCase(),difficulty:p.data.difficulty,suggestedMarks:p.data.suggestedMarks,tags:p.data.tags,reviewStatus:"pending",duplicateWarning:false,sourcePage:p.data.sourcePage??null,sourceReference:p.data.sourceReference??null,sourceAssetId:null});refresh();return{status:"success",message:"Draft Question updated."}}catch(e){return{status:"error",message:fail(e,"The draft Question could not be updated.")}}}
export async function createPracticeSetAction(input:unknown):Promise<PracticeActionResult<{id:string}>>{const p=practiceSetSchema.safeParse(input);if(!p.success)return{status:"error",message:"Correct the Practice Set fields.",fieldErrors:p.error.flatten().fieldErrors};try{const profile=await requireRole(DASHBOARD_ROLES);const id=await createPracticeSet(profile,p.data);refresh();return{status:"success",message:"Draft Practice Set created with immutable Question snapshots.",data:{id}}}catch(e){return{status:"error",message:fail(e,"We could not create the Practice Set.")}}}
export async function publishPracticeSetAction(input:unknown):Promise<PracticeActionResult>{const p=practiceSetIdSchema.safeParse(input);if(!p.success)return{status:"error",message:"Invalid Practice Set."};try{const r=await publishPracticeSet(p.data.id);refresh();return{status:"success",message:`Published ${r.questionCount} Questions · ${r.totalMarks} marks.`}}catch(e){return{status:"error",message:fail(e,"We could not publish the Practice Set.")}}}
export async function assignPracticeSetAction(input:unknown):Promise<PracticeActionResult>{const p=assignmentSchema.safeParse(input);if(!p.success)return{status:"error",message:"Correct the assignment fields.",fieldErrors:p.error.flatten().fieldErrors};try{await requireRole(DASHBOARD_ROLES);const r=await assignPracticeSet(p.data);refresh();return{status:"success",message:`Assigned to ${r.assignedCount} Student${r.assignedCount===1?"":"s"}.`}}catch(e){return{status:"error",message:fail(e,"We could not assign this Practice Set.")}}}
export async function startPracticeAttemptAction(input:unknown):Promise<PracticeActionResult<AttemptSession>>{const p=attemptStartSchema.safeParse(input);if(!p.success)return{status:"error",message:"Invalid assignment."};try{await requireRole(["Student"]);return{status:"success",message:"Attempt started.",data:await startAttempt(p.data.assignmentId)}}catch(e){return{status:"error",message:fail(e,"We could not start this attempt.")}}}
export async function submitPracticeAttemptAction(input:unknown):Promise<PracticeActionResult<SubmitAttemptResult>>{const p=attemptSubmitSchema.safeParse(input);if(!p.success)return{status:"error",message:"Answer every required Question."};try{await requireRole(["Student"]);const data=await submitAttempt(p.data.attemptId,p.data.answers);revalidatePath("/practice-work/my-work");return{status:"success",message:"Practice submitted. Review your answers and explanations.",data}}catch(e){return{status:"error",message:fail(e,"We could not submit this attempt.")}}}
export async function retryIncorrectAction(input:unknown):Promise<PracticeActionResult<AttemptSession>>{const p=retrySchema.safeParse(input);if(!p.success)return{status:"error",message:"Invalid attempt."};try{await requireRole(["Student"]);return{status:"success",message:"Retry created for incorrect Questions.",data:await createRetry(p.data.attemptId)}}catch(e){return{status:"error",message:fail(e,"We could not create this retry.")}}}
