"use server";
import { revalidatePath } from "next/cache";
import { aiGenerationSchema,generationReviewSchema } from "@/features/practice-work/schemas/ai-generation-schema";
import { questionIdSchema,questionSchema,questionTemplateSchema } from "@/features/practice-work/schemas/question-schema";
import { assignmentSchema,attemptStartSchema,attemptSubmitSchema,practiceSetIdSchema,practiceSetSchema,retrySchema } from "@/features/practice-work/schemas/practice-set-schema";
import { generateQuestionsWithAi,reviewGeneratedQuestions } from "@/features/practice-work/services/ai-question-service";
import { createRetry,startAttempt,submitAttempt } from "@/features/practice-work/services/practice-attempt-service";
import { assignPracticeSet,createPracticeSet,createRecommendedTemplates,deactivateTemplate,publishPracticeSet,saveBankQuestion,saveTemplate } from "@/features/practice-work/services/practice-work-service";
import type { PracticeActionResult,AttemptSession,SubmitAttemptResult } from "@/features/practice-work/types/practice-work";
import { requireRole } from "@/lib/auth/services/auth-service";
import { DASHBOARD_ROLES } from "@/lib/navigation";
const paths=["/practice-work","/practice-work/question-bank","/practice-work/templates","/practice-work/generations","/practice-work/sets","/practice-work/assignments"];
const refresh=()=>paths.forEach(p=>revalidatePath(p));
export async function createRecommendedTemplatesAction():Promise<PracticeActionResult>{try{const profile=await requireRole(DASHBOARD_ROLES);await createRecommendedTemplates(profile);refresh();return{status:"success",message:"Recommended Templates are ready."}}catch{return{status:"error",message:"We could not create the recommended Templates."}}}
const fail=(error:unknown,fallback:string)=>{const m=error instanceof Error?error.message:"";return m.includes("DUPLICATE")?"A similar Question already exists. Review the duplicate warning before overriding.":m.includes("TARGET_MARKS")?"Question marks do not match the Target Total Marks.":m.includes("OPENAI_NOT_CONFIGURED")?"OpenAI generation is not configured.":m.includes("PRACTICE_MAX_ATTEMPTS")?"The maximum number of attempts has been reached.":m.includes("PRACTICE_ANSWERS_INCOMPLETE")?"Answer every Question before submitting.":fallback};
export async function saveTemplateAction(input:unknown):Promise<PracticeActionResult<{id:string}>>{const p=questionTemplateSchema.safeParse(input);if(!p.success)return{status:"error",message:"Correct the Template fields.",fieldErrors:p.error.flatten().fieldErrors};try{const profile=await requireRole(DASHBOARD_ROLES);const id=await saveTemplate(profile,p.data);refresh();return{status:"success",message:"Question Template saved.",data:{id}}}catch(e){return{status:"error",message:fail(e,"We could not save the Question Template.")}}}
export async function deactivateTemplateAction(input:unknown):Promise<PracticeActionResult>{const p=questionIdSchema.safeParse(input);if(!p.success)return{status:"error",message:"Invalid Template."};try{await requireRole(DASHBOARD_ROLES).then(profile=>deactivateTemplate(profile,p.data.id));refresh();return{status:"success",message:"Question Template deactivated."}}catch(e){return{status:"error",message:fail(e,"We could not deactivate the Template.")}}}
export async function saveQuestionAction(input:unknown):Promise<PracticeActionResult<{id:string}>>{const p=questionSchema.safeParse(input);if(!p.success)return{status:"error",message:"Correct the Question fields.",fieldErrors:p.error.flatten().fieldErrors};try{const profile=await requireRole(DASHBOARD_ROLES);const id=await saveBankQuestion(profile,{id:p.data.id,boardId:p.data.boardId??null,classId:p.data.classId??null,bookName:p.data.bookName??null,chapter:p.data.chapter??null,skill:p.data.skill??null,topic:p.data.topic??null,subtopic:p.data.subtopic??null,templateId:p.data.templateId??null,questionType:p.data.questionType,questionText:p.data.questionText,options:p.data.options??null,correctAnswer:p.data.correctAnswer,acceptedAnswers:p.data.acceptedAnswers??null,answerExplanation:p.data.answerExplanation??null,difficulty:p.data.difficulty,suggestedMarks:p.data.suggestedMarks??null});refresh();return{status:"success",message:"Question saved to the Question Bank.",data:{id}}}catch(e){return{status:"error",message:fail(e,"We could not save this Question.")}}}
export async function generateQuestionsAction(input:unknown):Promise<PracticeActionResult<{generationId:string}>>{const p=aiGenerationSchema.safeParse(input);if(!p.success)return{status:"error",message:"Correct the generation fields.",fieldErrors:p.error.flatten().fieldErrors};try{const profile=await requireRole(DASHBOARD_ROLES);const generationId=await generateQuestionsWithAi(profile,p.data);refresh();return{status:"success",message:"Questions generated for review. Nothing was added to the Question Bank.",data:{generationId}}}catch(e){return{status:"error",message:fail(e,"AI generation failed. Please try again.")}}}
export async function reviewGeneratedQuestionsAction(input:unknown):Promise<PracticeActionResult>{const p=generationReviewSchema.safeParse(input);if(!p.success)return{status:"error",message:"Select Questions to review."};try{const profile=await requireRole(DASHBOARD_ROLES);const r=await reviewGeneratedQuestions(profile,p.data);refresh();return{status:"success",message:`Review saved: ${r.approved} approved, ${r.rejected} rejected.`}}catch(e){return{status:"error",message:fail(e,"We could not save the review.")}}}
export async function createPracticeSetAction(input:unknown):Promise<PracticeActionResult<{id:string}>>{const p=practiceSetSchema.safeParse(input);if(!p.success)return{status:"error",message:"Correct the Practice Set fields.",fieldErrors:p.error.flatten().fieldErrors};try{const profile=await requireRole(DASHBOARD_ROLES);const id=await createPracticeSet(profile,p.data);refresh();return{status:"success",message:"Draft Practice Set created with immutable Question snapshots.",data:{id}}}catch(e){return{status:"error",message:fail(e,"We could not create the Practice Set.")}}}
export async function publishPracticeSetAction(input:unknown):Promise<PracticeActionResult>{const p=practiceSetIdSchema.safeParse(input);if(!p.success)return{status:"error",message:"Invalid Practice Set."};try{const r=await publishPracticeSet(p.data.id);refresh();return{status:"success",message:`Published ${r.questionCount} Questions · ${r.totalMarks} marks.`}}catch(e){return{status:"error",message:fail(e,"We could not publish the Practice Set.")}}}
export async function assignPracticeSetAction(input:unknown):Promise<PracticeActionResult>{const p=assignmentSchema.safeParse(input);if(!p.success)return{status:"error",message:"Correct the assignment fields.",fieldErrors:p.error.flatten().fieldErrors};try{await requireRole(DASHBOARD_ROLES);const r=await assignPracticeSet(p.data);refresh();return{status:"success",message:`Assigned to ${r.assignedCount} Student${r.assignedCount===1?"":"s"}.`}}catch(e){return{status:"error",message:fail(e,"We could not assign this Practice Set.")}}}
export async function startPracticeAttemptAction(input:unknown):Promise<PracticeActionResult<AttemptSession>>{const p=attemptStartSchema.safeParse(input);if(!p.success)return{status:"error",message:"Invalid assignment."};try{await requireRole(["Student"]);return{status:"success",message:"Attempt started.",data:await startAttempt(p.data.assignmentId)}}catch(e){return{status:"error",message:fail(e,"We could not start this attempt.")}}}
export async function submitPracticeAttemptAction(input:unknown):Promise<PracticeActionResult<SubmitAttemptResult>>{const p=attemptSubmitSchema.safeParse(input);if(!p.success)return{status:"error",message:"Answer every required Question."};try{await requireRole(["Student"]);const data=await submitAttempt(p.data.attemptId,p.data.answers);revalidatePath("/practice-work/my-work");return{status:"success",message:"Practice submitted. Review your answers and explanations.",data}}catch(e){return{status:"error",message:fail(e,"We could not submit this attempt.")}}}
export async function retryIncorrectAction(input:unknown):Promise<PracticeActionResult<AttemptSession>>{const p=retrySchema.safeParse(input);if(!p.success)return{status:"error",message:"Invalid attempt."};try{await requireRole(["Student"]);return{status:"success",message:"Retry created for incorrect Questions.",data:await createRetry(p.data.attemptId)}}catch(e){return{status:"error",message:fail(e,"We could not create this retry.")}}}
