BEGIN;
DROP FUNCTION IF EXISTS public.schedule_pending_replacement(uuid,date,time,time,text);
DROP FUNCTION IF EXISTS public.cancel_planner_event(uuid,text,boolean);
DROP FUNCTION IF EXISTS public.create_planner_event(jsonb);
DROP FUNCTION IF EXISTS public.queue_planner_whatsapp(uuid,text);
DROP FUNCTION IF EXISTS public.replace_batch_timetable(uuid,date,jsonb,boolean,text);
DROP FUNCTION IF EXISTS public.create_teaching_batch(jsonb,boolean);
DROP TABLE IF EXISTS public.planner_message_outbox;
DROP TABLE IF EXISTS public.batch_schedule_overlap_approvals;
DROP INDEX IF EXISTS public.schedule_events_pending_idx;
DROP INDEX IF EXISTS public.schedule_events_related_event_idx;
ALTER TABLE public.schedule_events DROP CONSTRAINT IF EXISTS schedule_events_pending_check,DROP CONSTRAINT IF EXISTS schedule_events_pending_resolved_by_fkey,DROP CONSTRAINT IF EXISTS schedule_events_related_event_fkey,DROP COLUMN IF EXISTS reschedule_pending_resolved_by,DROP COLUMN IF EXISTS reschedule_pending_resolved_at,DROP COLUMN IF EXISTS reschedule_pending,DROP COLUMN IF EXISTS related_event_id,DROP CONSTRAINT IF EXISTS schedule_events_type_check,ADD CONSTRAINT schedule_events_type_check CHECK(schedule_type IN ('regular_class','practice_work','practice_test','mock_test','exam','parent_meeting','holiday','special_class'));
ALTER TABLE public.class_schedules DROP CONSTRAINT IF EXISTS class_schedules_type_check,ADD CONSTRAINT class_schedules_type_check CHECK(schedule_type IN ('regular_class','practice_work','practice_test','mock_test','exam','parent_meeting','holiday','special_class'));
DROP INDEX IF EXISTS public.batches_branch_idx;
DROP INDEX IF EXISTS public.batches_academic_year_idx;
DROP INDEX IF EXISTS public.batches_active_academic_identity_key;
ALTER TABLE public.batches DROP CONSTRAINT IF EXISTS batches_teaching_identity_check,DROP CONSTRAINT IF EXISTS batches_branch_fkey,DROP CONSTRAINT IF EXISTS batches_academic_year_fkey,DROP COLUMN IF EXISTS branch_id,DROP COLUMN IF EXISTS academic_year_id;
ALTER TABLE public.batches DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS batches_admin_select ON public.batches;
DROP POLICY IF EXISTS batches_student_select ON public.batches;
DROP POLICY IF EXISTS batches_parent_select ON public.batches;
GRANT ALL ON public.batches TO anon,authenticated;
COMMIT;
