BEGIN;
DO $$ BEGIN IF EXISTS(SELECT 1 FROM public.question_bank WHERE source_type='import') OR EXISTS(SELECT 1 FROM public.practice_question_source_files WHERE status='approved') THEN RAISE EXCEPTION 'ROLLBACK_REFUSED: imported Practice Work history exists'; END IF; END $$;
DROP FUNCTION public.seed_practice_question_templates();
DROP POLICY IF EXISTS practice_work_private_select ON storage.objects;
DROP POLICY IF EXISTS practice_work_private_insert ON storage.objects;
DROP POLICY IF EXISTS practice_work_private_update ON storage.objects;
DROP POLICY IF EXISTS practice_work_private_delete ON storage.objects;
DELETE FROM storage.buckets WHERE id='practice-work-private' AND NOT EXISTS(SELECT 1 FROM storage.objects WHERE bucket_id='practice-work-private');
ALTER TABLE public.question_templates DROP COLUMN blueprint;
ALTER TABLE public.question_bank DROP CONSTRAINT question_bank_source_asset_fkey,DROP CONSTRAINT question_bank_source_file_fkey,DROP CONSTRAINT question_bank_subject_fkey,DROP CONSTRAINT question_bank_source_page_check,DROP CONSTRAINT question_bank_source_marks_check,DROP CONSTRAINT question_bank_source_check;
ALTER TABLE public.question_bank ADD CONSTRAINT question_bank_source_check CHECK(source_type IN ('manual','ai'));
ALTER TABLE public.question_bank DROP COLUMN subject_id,DROP COLUMN source_full_marks,DROP COLUMN question_exam_date,DROP COLUMN source_file_id,DROP COLUMN source_page,DROP COLUMN source_asset_id;
ALTER TABLE public.ai_generated_questions DROP CONSTRAINT ai_generated_asset_fkey,DROP COLUMN source_page,DROP COLUMN source_reference,DROP COLUMN source_asset_id;
ALTER TABLE public.ai_question_generations DROP CONSTRAINT ai_generations_source_requirements_check,DROP CONSTRAINT ai_generations_source_file_fkey,DROP CONSTRAINT ai_generations_subject_fkey,DROP CONSTRAINT ai_generations_source_marks_check,DROP CONSTRAINT ai_generations_source_check,DROP CONSTRAINT ai_generations_status_check;
ALTER TABLE public.ai_question_generations ADD CONSTRAINT ai_generations_status_check CHECK(status IN ('pending','completed','failed','reviewed'));
ALTER TABLE public.ai_question_generations ALTER COLUMN template_id SET NOT NULL; ALTER TABLE public.ai_question_generations ALTER COLUMN model SET NOT NULL;
ALTER TABLE public.ai_question_generations DROP COLUMN source_type,DROP COLUMN subject_id,DROP COLUMN source_full_marks,DROP COLUMN question_exam_date,DROP COLUMN source_file_id;
DROP TABLE public.practice_question_assets; DROP TABLE public.practice_question_source_files;
COMMIT;
