BEGIN;
REVOKE ALL ON FUNCTION public.create_practice_retry(uuid),public.submit_practice_attempt(uuid,jsonb),public.start_practice_attempt(uuid),public.assign_practice_set(uuid,uuid,uuid[],timestamptz,timestamptz,uuid),public.publish_practice_set(uuid),public.practice_work_student_id(uuid),public.practice_work_admin_scope(uuid) FROM PUBLIC,anon,authenticated;
DROP FUNCTION public.create_practice_retry(uuid);
DROP FUNCTION public.submit_practice_attempt(uuid,jsonb);
DROP FUNCTION public.start_practice_attempt(uuid);
DROP FUNCTION public.assign_practice_set(uuid,uuid,uuid[],timestamptz,timestamptz,uuid);
DROP FUNCTION public.publish_practice_set(uuid);
DROP FUNCTION public.practice_work_student_id(uuid);
DROP FUNCTION public.practice_work_admin_scope(uuid);
DROP TABLE public.practice_attempt_answers;
DROP TABLE public.practice_attempts;
DROP TABLE public.practice_assignments;
DROP TABLE public.practice_set_questions;
DROP TABLE public.practice_sets;
DROP TABLE public.question_bank;
DROP TABLE public.ai_generated_questions;
DROP TABLE public.ai_question_generations;
DROP TABLE public.question_templates;
COMMIT;
